/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommentDtoV1 } from "./comment-dto-v1.ts";

/**
 * CommentsListDtoV1
 * @description Список комментариев документа
 * @example [object Object],[object Object]
 */
export type CommentsListDtoV1 = CommentDtoV1[];
