/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserMetaDataDtoV1 } from "./user-meta-data-dto-v1.ts";

/**
 * CommentDtoV1
 * @description Модель комментария
 * @example [object Object]
 */
export type CommentDtoV1 = {
  /**
   * @description ID комментария
   * @minLength 1
   * @type integer, int64
   */
  id: number;
  /**
   * @description Текст комментария
   * @type string
   */
  text: string;
  /**
   * @description Дата создания
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @description Ограниченные данные о пользователе
   * @type object
   */
  author: UserMetaDataDtoV1;
  /**
   * @description Список дочерних комментариев
   * @type array
   */
  children: CommentDtoV1[];
};
