/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryRequestV1 } from "./document-category-request-v1.ts";
import type { DocumentCategoryResponseV1 } from "./document-category-response-v1.ts";

/**
 * DocumentCategoryResponseV1
 * @description Успешный запрос
 * @example [object Object]
 */
export type CreateDocumentCategoryV1201 = DocumentCategoryResponseV1;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type CreateDocumentCategoryV1400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type CreateDocumentCategoryV1401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type CreateDocumentCategoryV1403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type CreateDocumentCategoryV1500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * DocumentCategoryRequestV1
 * @example [object Object]
 */
export type CreateDocumentCategoryV1MutationRequest = DocumentCategoryRequestV1;

export type CreateDocumentCategoryV1MutationResponse =
  CreateDocumentCategoryV1201;

export type CreateDocumentCategoryV1Mutation = {
  Response: CreateDocumentCategoryV1201;
  Request: CreateDocumentCategoryV1MutationRequest;
  Errors:
    | CreateDocumentCategoryV1400
    | CreateDocumentCategoryV1401
    | CreateDocumentCategoryV1403
    | CreateDocumentCategoryV1500;
};
