/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryV1 } from "./document-category-v1.ts";
import type { PaginationMetaV1 } from "./pagination-meta-v1.ts";

/**
 * DocumentCategoryListResponseV1
 * @description Модель ответа - Список категорий документов
 * @example [object Object]
 */
export type DocumentCategoryListResponseV1 = PaginationMetaV1 & {
  /**
   * @description Список категорий
   * @type array | undefined
   */
  content?: DocumentCategoryV1[];
};
