/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryV1 } from "./document-category-v1.ts";
import type { DocumentMetaDtoV1 } from "./document-meta-dto-v1.ts";
import type { PaginationMetaV1 } from "./pagination-meta-v1.ts";

/**
 * DocumentCategoryResponseV1
 * @description Информация о категории
 * @example [object Object]
 */
export type DocumentCategoryResponseV1 = {
  /**
   * @description Список категорий
   * @type object
   */
  category: DocumentCategoryV1;
  /**
   * @description Модель пагинации
   * @type object
   */
  pageInfo: PaginationMetaV1;
  /**
   * @description Список документов в категории
   * @type array
   */
  documents: DocumentMetaDtoV1[];
};
