/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentBlockImageV1 } from "./document-block-image-v1.ts";
import type { DocumentBlockParagraphV1 } from "./document-block-paragraph-v1.ts";
import type { DocumentBlockTitleV1 } from "./document-block-title-v1.ts";
import type { DocumentCategoryV1 } from "./document-category-v1.ts";
import type { DocumentMetaDtoV1 } from "./document-meta-dto-v1.ts";

/**
 * DocumentResponseV1
 * @example [object Object]
 */
export type DocumentResponseV1 = DocumentMetaDtoV1 & {
  /**
   * @type array
   */
  content: (
    | DocumentBlockTitleV1
    | DocumentBlockParagraphV1
    | DocumentBlockImageV1
  )[];
  /**
   * @description Список категорий
   * @type object
   */
  category: DocumentCategoryV1;
};
