/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DocumentBlockParagraphV1TypeEnum = "paragraph";

/**
 * DocumentBlockParagraphV1
 * @description Блок документа - Параграф
 * @example [object Object]
 */
export type DocumentBlockParagraphV1 = {
  /**
   * @description ID блока документа
   * @type integer, int64
   */
  id: number;
  /**
   * @description Тип блока
   * @type string
   */
  type: DocumentBlockParagraphV1TypeEnum;
  /**
   * @description Порядковый номер блока в документе
   * @minLength 1
   * @type integer, int64
   */
  position: number;
  /**
   * @description Значение поля
   * @type string
   */
  value: string;
};
