/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DocumentBlockImageV1TypeEnum = "image";

/**
 * DocumentBlockImageV1
 * @description Блок документа - Картинка
 * @example [object Object]
 */
export type DocumentBlockImageV1 = {
  /**
   * @description ID блока
   * @type integer, int64
   */
  id: number;
  /**
   * @description Тип блока
   * @type string
   */
  type: DocumentBlockImageV1TypeEnum;
  /**
   * @description Порядковый номер блока в документе
   * @minLength 1
   * @type integer, int64
   */
  position: number;
  /**
   * @description Настройки блока с картинкой
   * @type object
   */
  settings: {
    /**
     * @description Название картинки
     * @type string
     */
    title: string;
    /**
     * @description URL картинки
     * @type string, uri
     */
    src: string;
    /**
     * @description Ширина картинки
     * @minLength 0
     * @default 100
     * @type integer | undefined, int64
     */
    width?: number;
    /**
     * @description Высота картинки
     * @minLength 0
     * @default 100
     * @type integer | undefined, int64
     */
    height?: number;
  };
};
