/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * DocumentCategoryV1
 * @description Список категорий
 * @example [object Object]
 */
export type DocumentCategoryV1 = {
  /**
   * @description ID категории документа
   * @type string, uuid
   */
  id: string;
  /**
   * @description Название категории
   * @type string
   */
  title: string;
  /**
   * @description Количество документов в категории
   * @minLength 0
   * @type integer, int64
   */
  countDocuments: number;
};
