/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DocumentTypeEnumV1Enum = "PUBLIC" | "PRIVATE";

/**
 * DocumentTypeEnumV1
 * @description Тип документа
 * @example PUBLIC
 */
export type DocumentTypeEnumV1 = DocumentTypeEnumV1Enum;
