/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type DocumentBlockTitleV1TypeEnum = "header";

export type DocumentBlockTitleV1LevelEnum = "1" | "2" | "3" | "4" | "5" | "6";

/**
 * DocumentBlockTitleV1
 * @description Блок документа - Заголовок
 * @example [object Object]
 */
export type DocumentBlockTitleV1 = {
  /**
   * @description ID блока документа
   * @type integer, int64
   */
  id: number;
  /**
   * @description Тип блока
   * @type string
   */
  type: DocumentBlockTitleV1TypeEnum;
  /**
   * @description Уровень заголовка
   * @type string
   */
  level: DocumentBlockTitleV1LevelEnum;
  /**
   * @description Порядковый номер блока в документе
   * @minLength 1
   * @type integer, int64
   */
  position: number;
  /**
   * @description Значение поля
   * @type string
   */
  value: string;
};
