/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentTypeEnumV1 } from "./document-type-enum-v1.ts";
import type { UserMetaDataDtoV1 } from "./user-meta-data-dto-v1.ts";

/**
 * DocumentMetaDtoV1
 * @description Базовая модель документа
 * @example [object Object]
 */
export type DocumentMetaDtoV1 = {
  /**
   * @description ID документа
   * @type integer, int64
   */
  id: number;
  /**
   * @description Название
   * @type string
   */
  title: string;
  /**
   * @description Описание документа
   * @type string | undefined
   */
  description?: string;
  /**
   * @description Дата создания
   * @type string, date-time
   */
  createdAt: string;
  /**
   * @description Дата обновления
   * @type string, date-time
   */
  updatedAt: string | null;
  /**
   * @description Количество комментариев к документу
   * @minLength 0
   * @type integer, int32
   */
  comments: number;
  /**
   * @description Ограниченные данные о пользователе
   * @type object
   */
  createdBy: UserMetaDataDtoV1;
  /**
   * @description Тип документа
   * @type string
   */
  type: DocumentTypeEnumV1;
};
