/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * DocumentCategoryRequestV1
 * @description Модель создания / обновления категории документов
 * @example [object Object]
 */
export type DocumentCategoryRequestV1 = {
  /**
   * @description Название категории
   * @type string
   */
  title: string;
};
