/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommentsListDtoV1 } from "./comments-list-dto-v1.ts";

export type GetCommentsByDocumentIdPathParams = {
  /**
   * @description ID документа
   * @minLength 1
   * @type integer, int64
   */
  documentId: number;
};

/**
 * CommentsListDtoV1
 * @description Успешный запрос
 * @example [object Object],[object Object]
 */
export type GetCommentsByDocumentId200 = CommentsListDtoV1;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type GetCommentsByDocumentId400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type GetCommentsByDocumentId401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type GetCommentsByDocumentId403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export type GetCommentsByDocumentId404 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type GetCommentsByDocumentId500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

export type GetCommentsByDocumentIdQueryResponse = GetCommentsByDocumentId200;

export type GetCommentsByDocumentIdQuery = {
  Response: GetCommentsByDocumentId200;
  PathParams: GetCommentsByDocumentIdPathParams;
  Errors:
    | GetCommentsByDocumentId400
    | GetCommentsByDocumentId401
    | GetCommentsByDocumentId403
    | GetCommentsByDocumentId404
    | GetCommentsByDocumentId500;
};
