/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryListResponseV1 } from "./document-category-list-response-v1.ts";

/**
 * DocumentCategoryListResponseV1
 * @description Успешный запрос
 * @example [object Object]
 */
export type GetAllDocCategoriesV1200 = DocumentCategoryListResponseV1;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type GetAllDocCategoriesV1400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type GetAllDocCategoriesV1401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type GetAllDocCategoriesV1403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type GetAllDocCategoriesV1500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

export type GetAllDocCategoriesV1QueryResponse = GetAllDocCategoriesV1200;

export type GetAllDocCategoriesV1Query = {
  Response: GetAllDocCategoriesV1200;
  Errors:
    | GetAllDocCategoriesV1400
    | GetAllDocCategoriesV1401
    | GetAllDocCategoriesV1403
    | GetAllDocCategoriesV1500;
};
