/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryResponseV1 } from "./document-category-response-v1.ts";

export type GetDocumentsCategoryByIdPathParams = {
  /**
   * @description ID категории документов
   * @minLength 1
   * @type string, uuid
   */
  categoryId: string;
};

export type GetDocumentsCategoryByIdQueryParams = {
  /**
   * @description Номер страницы
   * @minLength 1
   * @default 1
   * @type integer | undefined, int64
   */
  page?: number;
  /**
   * @description По сколько элементов выводить на страницу
   * @minLength 1
   * @default 10
   * @type integer | undefined, int64
   */
  size?: number;
  /**
   * @description Направление сортировки. Например `name,desc`
   * @type array | undefined
   */
  sort?: string[];
};

/**
 * DocumentCategoryResponseV1
 * @description Успешный запрос
 * @example [object Object]
 */
export type GetDocumentsCategoryById200 = DocumentCategoryResponseV1;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type GetDocumentsCategoryById400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type GetDocumentsCategoryById401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type GetDocumentsCategoryById403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export type GetDocumentsCategoryById404 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type GetDocumentsCategoryById500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

export type GetDocumentsCategoryByIdQueryResponse = GetDocumentsCategoryById200;

export type GetDocumentsCategoryByIdQuery = {
  Response: GetDocumentsCategoryById200;
  PathParams: GetDocumentsCategoryByIdPathParams;
  QueryParams: GetDocumentsCategoryByIdQueryParams;
  Errors:
    | GetDocumentsCategoryById400
    | GetDocumentsCategoryById401
    | GetDocumentsCategoryById403
    | GetDocumentsCategoryById404
    | GetDocumentsCategoryById500;
};
