/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentResponseV1 } from "./document-response-v1.ts";

export type GetDocumentByIdPathParams = {
  /**
   * @description ID документа
   * @minLength 1
   * @type integer, int64
   */
  documentId: number;
};

/**
 * DocumentResponseV1
 * @description Успешный запрос
 * @example [object Object]
 */
export type GetDocumentById200 = DocumentResponseV1;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type GetDocumentById400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type GetDocumentById401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type GetDocumentById403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export type GetDocumentById404 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type GetDocumentById500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

export type GetDocumentByIdQueryResponse = GetDocumentById200;

export type GetDocumentByIdQuery = {
  Response: GetDocumentById200;
  PathParams: GetDocumentByIdPathParams;
  Errors:
    | GetDocumentById400
    | GetDocumentById401
    | GetDocumentById403
    | GetDocumentById404
    | GetDocumentById500;
};
