/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Модель ошибки, приходящей с сервера
 */
export type NotFoundError = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};
