/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * PaginateResponseDtoV1
 * @description Модель пагинации
 * @example [object Object]
 */
export type PaginationMetaV1 = {
  /**
   * @description Пришел ли пустой список проектов
   * @type boolean
   */
  empty: boolean;
  /**
   * @description Это была первая страница
   * @type boolean
   */
  first: boolean;
  /**
   * @description Это была последняя страница
   * @type boolean
   */
  last: boolean;
  /**
   * @description Номер страницы
   * @minLength 0
   * @type integer, int64
   */
  number: number;
  /**
   * @description Число элементов на странице
   * @minLength 0
   * @type integer, int64
   */
  numberOfElements: number;
  /**
   * @description Число элементов на странице
   * @minLength 0
   * @type integer, int64
   */
  size: number;
  /**
   * @description Всего элементов храниться в API
   * @minLength 0
   * @type integer, int64
   */
  totalElements: number;
  /**
   * @description Всего страниц для пагинации
   * @minLength 1
   * @type integer, int64
   */
  totalPages: number;
  /**
   * @description Настройки сортировки
   * @type object
   */
  sort: {
    /**
     * @description Пришел ли пустой список проектов
     * @type boolean
     */
    empty: boolean;
    /**
     * @description Отсортирован ли список
     * @type boolean
     */
    sorted: boolean;
    /**
     * @description Пришел ли не отсортированный список
     * @type boolean
     */
    unsorted: boolean;
  };
  /**
   * @description Настройки пагинации
   * @type object
   */
  pageable: {
    /**
     * @description Смещение пагинации
     * @minLength 0
     * @type integer, int64
     */
    offset: number;
    /**
     * @description Номер страницы
     * @minLength 0
     * @type integer, int64
     */
    pageNumber: number;
    /**
     * @description Число элементов на странице
     * @minLength 0
     * @type integer, int64
     */
    pageSize: number;
    /**
     * @description Неизвестное поле
     * @type boolean
     */
    paged: boolean;
    /**
     * @description Неизвестное поле
     * @type boolean
     */
    unpaged: boolean;
    /**
     * @description Настройки сортировки
     * @type object
     */
    sort: {
      /**
       * @description Пришел ли пустой список проектов
       * @type boolean | undefined
       */
      empty?: boolean;
      /**
       * @description Отсортирован ли список
       * @type boolean | undefined
       */
      sorted?: boolean;
      /**
       * @description Пришел ли не отсортированный список
       * @type boolean | undefined
       */
      unsorted?: boolean;
    };
  };
};
