/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export type RemoveDocumentCategoryByIdPathParams = {
  /**
   * @description ID категории документов
   * @minLength 1
   * @type string, uuid
   */
  categoryId: string;
};

/**
 * @description Успешный запрос
 */
export type RemoveDocumentCategoryById204 = unknown;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type RemoveDocumentCategoryById400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type RemoveDocumentCategoryById401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type RemoveDocumentCategoryById403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export type RemoveDocumentCategoryById404 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type RemoveDocumentCategoryById500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

export type RemoveDocumentCategoryByIdMutationResponse =
  RemoveDocumentCategoryById204;

export type RemoveDocumentCategoryByIdMutation = {
  Response: RemoveDocumentCategoryById204;
  PathParams: RemoveDocumentCategoryByIdPathParams;
  Errors:
    | RemoveDocumentCategoryById400
    | RemoveDocumentCategoryById401
    | RemoveDocumentCategoryById403
    | RemoveDocumentCategoryById404
    | RemoveDocumentCategoryById500;
};
