/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryRequestV1 } from "./document-category-request-v1.ts";
import type { DocumentCategoryResponseV1 } from "./document-category-response-v1.ts";

export type UpdateDocumentCategoryByIdPathParams = {
  /**
   * @description ID категории документов
   * @minLength 1
   * @type string, uuid
   */
  categoryId: string;
};

/**
 * DocumentCategoryResponseV1
 * @description Успешный запрос
 * @example [object Object]
 */
export type UpdateDocumentCategoryById200 = DocumentCategoryResponseV1;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export type UpdateDocumentCategoryById400 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export type UpdateDocumentCategoryById401 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export type UpdateDocumentCategoryById403 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export type UpdateDocumentCategoryById404 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * @description Ошибка сервера
 */
export type UpdateDocumentCategoryById500 = {
  /**
   * @description Текст ошибки
   * @type string
   */
  message: string;
};

/**
 * DocumentCategoryRequestV1
 * @example [object Object]
 */
export type UpdateDocumentCategoryByIdMutationRequest =
  DocumentCategoryRequestV1;

export type UpdateDocumentCategoryByIdMutationResponse =
  UpdateDocumentCategoryById200;

export type UpdateDocumentCategoryByIdMutation = {
  Response: UpdateDocumentCategoryById200;
  Request: UpdateDocumentCategoryByIdMutationRequest;
  PathParams: UpdateDocumentCategoryByIdPathParams;
  Errors:
    | UpdateDocumentCategoryById400
    | UpdateDocumentCategoryById401
    | UpdateDocumentCategoryById403
    | UpdateDocumentCategoryById404
    | UpdateDocumentCategoryById500;
};
