/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * UserMetaDataDtoV1
 * @description Ограниченные данные о пользователе
 * @example [object Object]
 */
export type UserMetaDataDtoV1 = {
  /**
   * @description ID пользователя
   * @type integer, int64
   */
  id: number;
  /**
   * @description Имя пользователя
   * @minLength 3
   * @maxLength 50
   * @type string
   */
  firstName: string;
  /**
   * @description Фамилия пользователя
   * @minLength 2
   * @maxLength 50
   * @type string
   */
  lastName: string;
  /**
   * @description URL аватарки пользователя
   * @type string, uri
   */
  avatarUrl: string | null;
};
