/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './../../app/routes/__root'
import { Route as UnsignedRouteImport } from './../../app/routes/_unsigned'
import { Route as ErrorsRouteImport } from './../../app/routes/_errors'
import { Route as AuthRouteImport } from './../../app/routes/_auth'
import { Route as AuthIndexRouteImport } from './../../app/routes/_auth/index'
import { Route as UnsignedLoginRouteImport } from './../../app/routes/_unsigned/login'
import { Route as Errors500RouteImport } from './../../app/routes/_errors/500'
import { Route as Errors404RouteImport } from './../../app/routes/_errors/404'
import { Route as AuthServicesRouteImport } from './../../app/routes/_auth/services'
import { Route as AuthPostsRouteImport } from './../../app/routes/_auth/posts'
import { Route as AuthFaqRouteImport } from './../../app/routes/_auth/faq'
import { Route as AuthContactsRouteImport } from './../../app/routes/_auth/contacts'
import { Route as AuthAboutRouteImport } from './../../app/routes/_auth/about'
import { Route as AuthPathlessLayoutRouteImport } from './../../app/routes/_auth/_pathlessLayout'
import { Route as AuthSettingsRouteRouteImport } from './../../app/routes/_auth/settings/route'
import { Route as AuthDocumentsRouteRouteImport } from './../../app/routes/_auth/documents/route'
import { Route as AuthBlogRouteRouteImport } from './../../app/routes/_auth/blog/route'
import { Route as AuthAppRouteRouteImport } from './../../app/routes/_auth/app/route'
import { Route as AuthPostsIndexRouteImport } from './../../app/routes/_auth/posts.index'
import { Route as AuthDocumentsIndexRouteImport } from './../../app/routes/_auth/documents/index'
import { Route as AuthBlogIndexRouteImport } from './../../app/routes/_auth/blog/index'
import { Route as AuthSettingsProfileRouteImport } from './../../app/routes/_auth/settings/profile'
import { Route as AuthSettingsNotificationsRouteImport } from './../../app/routes/_auth/settings/notifications'
import { Route as AuthPostsPostIdRouteImport } from './../../app/routes/_auth/posts.$postId'
import { Route as AuthBlogCreateRouteImport } from './../../app/routes/_auth/blog/create'
import { Route as AuthAppSettingsRouteImport } from './../../app/routes/_auth/app/settings'
import { Route as AuthAppDashboardRouteImport } from './../../app/routes/_auth/app/dashboard'
import { Route as AuthPathlessLayoutBRouteImport } from './../../app/routes/_auth/_pathlessLayout.b'
import { Route as AuthPathlessLayoutARouteImport } from './../../app/routes/_auth/_pathlessLayout.a'
import { Route as AuthDocumentsDocumentIdIndexRouteImport } from './../../app/routes/_auth/documents/$documentId/index'
import { Route as AuthPostsEditPostIdRouteImport } from './../../app/routes/_auth/posts.edit.$postId'
import { Route as AuthDocumentsCategoryCategoryIdRouteImport } from './../../app/routes/_auth/documents/category.$categoryId'
import { Route as AuthBlogPostIdModalRouteImport } from './../../app/routes/_auth/blog/$postId.modal'
import { Route as AuthBlogPostPostIdViewRouteImport } from './../../app/routes/_auth/blog/post.$postId.view'
import { Route as AuthBlogPostPostIdEditRouteImport } from './../../app/routes/_auth/blog/post.$postId.edit'

const UnsignedRoute = UnsignedRouteImport.update({
  id: '/_unsigned',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsRoute = ErrorsRouteImport.update({
  id: '/_errors',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const UnsignedLoginRoute = UnsignedLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnsignedRoute,
} as any)
const Errors500Route = Errors500RouteImport.update({
  id: '/500',
  path: '/500',
  getParentRoute: () => ErrorsRoute,
} as any)
const Errors404Route = Errors404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => ErrorsRoute,
} as any)
const AuthServicesRoute = AuthServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsRoute = AuthPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFaqRoute = AuthFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthRoute,
} as any)
const AuthContactsRoute = AuthContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAboutRoute = AuthAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPathlessLayoutRoute = AuthPathlessLayoutRouteImport.update({
  id: '/_pathlessLayout',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRouteRoute = AuthSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDocumentsRouteRoute = AuthDocumentsRouteRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBlogRouteRoute = AuthBlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAppRouteRoute = AuthAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPostsIndexRoute = AuthPostsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthPostsRoute,
} as any)
const AuthDocumentsIndexRoute = AuthDocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthDocumentsRouteRoute,
} as any)
const AuthBlogIndexRoute = AuthBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthBlogRouteRoute,
} as any)
const AuthSettingsProfileRoute = AuthSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthSettingsRouteRoute,
} as any)
const AuthSettingsNotificationsRoute =
  AuthSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthSettingsRouteRoute,
  } as any)
const AuthPostsPostIdRoute = AuthPostsPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => AuthPostsRoute,
} as any)
const AuthBlogCreateRoute = AuthBlogCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AuthBlogRouteRoute,
} as any)
const AuthAppSettingsRoute = AuthAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthAppDashboardRoute = AuthAppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthAppRouteRoute,
} as any)
const AuthPathlessLayoutBRoute = AuthPathlessLayoutBRouteImport.update({
  id: '/b',
  path: '/b',
  getParentRoute: () => AuthPathlessLayoutRoute,
} as any)
const AuthPathlessLayoutARoute = AuthPathlessLayoutARouteImport.update({
  id: '/a',
  path: '/a',
  getParentRoute: () => AuthPathlessLayoutRoute,
} as any)
const AuthDocumentsDocumentIdIndexRoute =
  AuthDocumentsDocumentIdIndexRouteImport.update({
    id: '/$documentId/',
    path: '/$documentId/',
    getParentRoute: () => AuthDocumentsRouteRoute,
  } as any)
const AuthPostsEditPostIdRoute = AuthPostsEditPostIdRouteImport.update({
  id: '/edit/$postId',
  path: '/edit/$postId',
  getParentRoute: () => AuthPostsRoute,
} as any)
const AuthDocumentsCategoryCategoryIdRoute =
  AuthDocumentsCategoryCategoryIdRouteImport.update({
    id: '/category/$categoryId',
    path: '/category/$categoryId',
    getParentRoute: () => AuthDocumentsRouteRoute,
  } as any)
const AuthBlogPostIdModalRoute = AuthBlogPostIdModalRouteImport.update({
  id: '/$postId/modal',
  path: '/$postId/modal',
  getParentRoute: () => AuthBlogRouteRoute,
} as any)
const AuthBlogPostPostIdViewRoute = AuthBlogPostPostIdViewRouteImport.update({
  id: '/post/$postId/view',
  path: '/post/$postId/view',
  getParentRoute: () => AuthBlogRouteRoute,
} as any)
const AuthBlogPostPostIdEditRoute = AuthBlogPostPostIdEditRouteImport.update({
  id: '/post/$postId/edit',
  path: '/post/$postId/edit',
  getParentRoute: () => AuthBlogRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/blog': typeof AuthBlogRouteRouteWithChildren
  '/documents': typeof AuthDocumentsRouteRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/about': typeof AuthAboutRoute
  '/contacts': typeof AuthContactsRoute
  '/faq': typeof AuthFaqRoute
  '/posts': typeof AuthPostsRouteWithChildren
  '/services': typeof AuthServicesRoute
  '/404': typeof Errors404Route
  '/500': typeof Errors500Route
  '/login': typeof UnsignedLoginRoute
  '/a': typeof AuthPathlessLayoutARoute
  '/b': typeof AuthPathlessLayoutBRoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/blog/create': typeof AuthBlogCreateRoute
  '/posts/$postId': typeof AuthPostsPostIdRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/blog/': typeof AuthBlogIndexRoute
  '/documents/': typeof AuthDocumentsIndexRoute
  '/posts/': typeof AuthPostsIndexRoute
  '/blog/$postId/modal': typeof AuthBlogPostIdModalRoute
  '/documents/category/$categoryId': typeof AuthDocumentsCategoryCategoryIdRoute
  '/posts/edit/$postId': typeof AuthPostsEditPostIdRoute
  '/documents/$documentId/': typeof AuthDocumentsDocumentIdIndexRoute
  '/blog/post/$postId/edit': typeof AuthBlogPostPostIdEditRoute
  '/blog/post/$postId/view': typeof AuthBlogPostPostIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthIndexRoute
  '/app': typeof AuthAppRouteRouteWithChildren
  '/settings': typeof AuthSettingsRouteRouteWithChildren
  '/about': typeof AuthAboutRoute
  '/contacts': typeof AuthContactsRoute
  '/faq': typeof AuthFaqRoute
  '/services': typeof AuthServicesRoute
  '/404': typeof Errors404Route
  '/500': typeof Errors500Route
  '/login': typeof UnsignedLoginRoute
  '/a': typeof AuthPathlessLayoutARoute
  '/b': typeof AuthPathlessLayoutBRoute
  '/app/dashboard': typeof AuthAppDashboardRoute
  '/app/settings': typeof AuthAppSettingsRoute
  '/blog/create': typeof AuthBlogCreateRoute
  '/posts/$postId': typeof AuthPostsPostIdRoute
  '/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/settings/profile': typeof AuthSettingsProfileRoute
  '/blog': typeof AuthBlogIndexRoute
  '/documents': typeof AuthDocumentsIndexRoute
  '/posts': typeof AuthPostsIndexRoute
  '/blog/$postId/modal': typeof AuthBlogPostIdModalRoute
  '/documents/category/$categoryId': typeof AuthDocumentsCategoryCategoryIdRoute
  '/posts/edit/$postId': typeof AuthPostsEditPostIdRoute
  '/documents/$documentId': typeof AuthDocumentsDocumentIdIndexRoute
  '/blog/post/$postId/edit': typeof AuthBlogPostPostIdEditRoute
  '/blog/post/$postId/view': typeof AuthBlogPostPostIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_errors': typeof ErrorsRouteWithChildren
  '/_unsigned': typeof UnsignedRouteWithChildren
  '/_auth/app': typeof AuthAppRouteRouteWithChildren
  '/_auth/blog': typeof AuthBlogRouteRouteWithChildren
  '/_auth/documents': typeof AuthDocumentsRouteRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRouteRouteWithChildren
  '/_auth/_pathlessLayout': typeof AuthPathlessLayoutRouteWithChildren
  '/_auth/about': typeof AuthAboutRoute
  '/_auth/contacts': typeof AuthContactsRoute
  '/_auth/faq': typeof AuthFaqRoute
  '/_auth/posts': typeof AuthPostsRouteWithChildren
  '/_auth/services': typeof AuthServicesRoute
  '/_errors/404': typeof Errors404Route
  '/_errors/500': typeof Errors500Route
  '/_unsigned/login': typeof UnsignedLoginRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/_pathlessLayout/a': typeof AuthPathlessLayoutARoute
  '/_auth/_pathlessLayout/b': typeof AuthPathlessLayoutBRoute
  '/_auth/app/dashboard': typeof AuthAppDashboardRoute
  '/_auth/app/settings': typeof AuthAppSettingsRoute
  '/_auth/blog/create': typeof AuthBlogCreateRoute
  '/_auth/posts/$postId': typeof AuthPostsPostIdRoute
  '/_auth/settings/notifications': typeof AuthSettingsNotificationsRoute
  '/_auth/settings/profile': typeof AuthSettingsProfileRoute
  '/_auth/blog/': typeof AuthBlogIndexRoute
  '/_auth/documents/': typeof AuthDocumentsIndexRoute
  '/_auth/posts/': typeof AuthPostsIndexRoute
  '/_auth/blog/$postId/modal': typeof AuthBlogPostIdModalRoute
  '/_auth/documents/category/$categoryId': typeof AuthDocumentsCategoryCategoryIdRoute
  '/_auth/posts/edit/$postId': typeof AuthPostsEditPostIdRoute
  '/_auth/documents/$documentId/': typeof AuthDocumentsDocumentIdIndexRoute
  '/_auth/blog/post/$postId/edit': typeof AuthBlogPostPostIdEditRoute
  '/_auth/blog/post/$postId/view': typeof AuthBlogPostPostIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/blog'
    | '/documents'
    | '/settings'
    | '/about'
    | '/contacts'
    | '/faq'
    | '/posts'
    | '/services'
    | '/404'
    | '/500'
    | '/login'
    | '/a'
    | '/b'
    | '/app/dashboard'
    | '/app/settings'
    | '/blog/create'
    | '/posts/$postId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/blog/'
    | '/documents/'
    | '/posts/'
    | '/blog/$postId/modal'
    | '/documents/category/$categoryId'
    | '/posts/edit/$postId'
    | '/documents/$documentId/'
    | '/blog/post/$postId/edit'
    | '/blog/post/$postId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/settings'
    | '/about'
    | '/contacts'
    | '/faq'
    | '/services'
    | '/404'
    | '/500'
    | '/login'
    | '/a'
    | '/b'
    | '/app/dashboard'
    | '/app/settings'
    | '/blog/create'
    | '/posts/$postId'
    | '/settings/notifications'
    | '/settings/profile'
    | '/blog'
    | '/documents'
    | '/posts'
    | '/blog/$postId/modal'
    | '/documents/category/$categoryId'
    | '/posts/edit/$postId'
    | '/documents/$documentId'
    | '/blog/post/$postId/edit'
    | '/blog/post/$postId/view'
  id:
    | '__root__'
    | '/_auth'
    | '/_errors'
    | '/_unsigned'
    | '/_auth/app'
    | '/_auth/blog'
    | '/_auth/documents'
    | '/_auth/settings'
    | '/_auth/_pathlessLayout'
    | '/_auth/about'
    | '/_auth/contacts'
    | '/_auth/faq'
    | '/_auth/posts'
    | '/_auth/services'
    | '/_errors/404'
    | '/_errors/500'
    | '/_unsigned/login'
    | '/_auth/'
    | '/_auth/_pathlessLayout/a'
    | '/_auth/_pathlessLayout/b'
    | '/_auth/app/dashboard'
    | '/_auth/app/settings'
    | '/_auth/blog/create'
    | '/_auth/posts/$postId'
    | '/_auth/settings/notifications'
    | '/_auth/settings/profile'
    | '/_auth/blog/'
    | '/_auth/documents/'
    | '/_auth/posts/'
    | '/_auth/blog/$postId/modal'
    | '/_auth/documents/category/$categoryId'
    | '/_auth/posts/edit/$postId'
    | '/_auth/documents/$documentId/'
    | '/_auth/blog/post/$postId/edit'
    | '/_auth/blog/post/$postId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ErrorsRoute: typeof ErrorsRouteWithChildren
  UnsignedRoute: typeof UnsignedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unsigned': {
      id: '/_unsigned'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnsignedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors': {
      id: '/_errors'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ErrorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_unsigned/login': {
      id: '/_unsigned/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnsignedLoginRouteImport
      parentRoute: typeof UnsignedRoute
    }
    '/_errors/500': {
      id: '/_errors/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof Errors500RouteImport
      parentRoute: typeof ErrorsRoute
    }
    '/_errors/404': {
      id: '/_errors/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof Errors404RouteImport
      parentRoute: typeof ErrorsRoute
    }
    '/_auth/services': {
      id: '/_auth/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthServicesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts': {
      id: '/_auth/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthPostsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/faq': {
      id: '/_auth/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthFaqRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/contacts': {
      id: '/_auth/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthContactsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/about': {
      id: '/_auth/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthAboutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/_pathlessLayout': {
      id: '/_auth/_pathlessLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthPathlessLayoutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/documents': {
      id: '/_auth/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthDocumentsRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/blog': {
      id: '/_auth/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof AuthBlogRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/app': {
      id: '/_auth/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthAppRouteRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/posts/': {
      id: '/_auth/posts/'
      path: '/'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthPostsIndexRouteImport
      parentRoute: typeof AuthPostsRoute
    }
    '/_auth/documents/': {
      id: '/_auth/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthDocumentsIndexRouteImport
      parentRoute: typeof AuthDocumentsRouteRoute
    }
    '/_auth/blog/': {
      id: '/_auth/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof AuthBlogIndexRouteImport
      parentRoute: typeof AuthBlogRouteRoute
    }
    '/_auth/settings/profile': {
      id: '/_auth/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof AuthSettingsProfileRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/settings/notifications': {
      id: '/_auth/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthSettingsNotificationsRouteImport
      parentRoute: typeof AuthSettingsRouteRoute
    }
    '/_auth/posts/$postId': {
      id: '/_auth/posts/$postId'
      path: '/$postId'
      fullPath: '/posts/$postId'
      preLoaderRoute: typeof AuthPostsPostIdRouteImport
      parentRoute: typeof AuthPostsRoute
    }
    '/_auth/blog/create': {
      id: '/_auth/blog/create'
      path: '/create'
      fullPath: '/blog/create'
      preLoaderRoute: typeof AuthBlogCreateRouteImport
      parentRoute: typeof AuthBlogRouteRoute
    }
    '/_auth/app/settings': {
      id: '/_auth/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AuthAppSettingsRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/app/dashboard': {
      id: '/_auth/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AuthAppDashboardRouteImport
      parentRoute: typeof AuthAppRouteRoute
    }
    '/_auth/_pathlessLayout/b': {
      id: '/_auth/_pathlessLayout/b'
      path: '/b'
      fullPath: '/b'
      preLoaderRoute: typeof AuthPathlessLayoutBRouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/_pathlessLayout/a': {
      id: '/_auth/_pathlessLayout/a'
      path: '/a'
      fullPath: '/a'
      preLoaderRoute: typeof AuthPathlessLayoutARouteImport
      parentRoute: typeof AuthPathlessLayoutRoute
    }
    '/_auth/documents/$documentId/': {
      id: '/_auth/documents/$documentId/'
      path: '/$documentId'
      fullPath: '/documents/$documentId/'
      preLoaderRoute: typeof AuthDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AuthDocumentsRouteRoute
    }
    '/_auth/posts/edit/$postId': {
      id: '/_auth/posts/edit/$postId'
      path: '/edit/$postId'
      fullPath: '/posts/edit/$postId'
      preLoaderRoute: typeof AuthPostsEditPostIdRouteImport
      parentRoute: typeof AuthPostsRoute
    }
    '/_auth/documents/category/$categoryId': {
      id: '/_auth/documents/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/documents/category/$categoryId'
      preLoaderRoute: typeof AuthDocumentsCategoryCategoryIdRouteImport
      parentRoute: typeof AuthDocumentsRouteRoute
    }
    '/_auth/blog/$postId/modal': {
      id: '/_auth/blog/$postId/modal'
      path: '/$postId/modal'
      fullPath: '/blog/$postId/modal'
      preLoaderRoute: typeof AuthBlogPostIdModalRouteImport
      parentRoute: typeof AuthBlogRouteRoute
    }
    '/_auth/blog/post/$postId/view': {
      id: '/_auth/blog/post/$postId/view'
      path: '/post/$postId/view'
      fullPath: '/blog/post/$postId/view'
      preLoaderRoute: typeof AuthBlogPostPostIdViewRouteImport
      parentRoute: typeof AuthBlogRouteRoute
    }
    '/_auth/blog/post/$postId/edit': {
      id: '/_auth/blog/post/$postId/edit'
      path: '/post/$postId/edit'
      fullPath: '/blog/post/$postId/edit'
      preLoaderRoute: typeof AuthBlogPostPostIdEditRouteImport
      parentRoute: typeof AuthBlogRouteRoute
    }
  }
}

interface AuthAppRouteRouteChildren {
  AuthAppDashboardRoute: typeof AuthAppDashboardRoute
  AuthAppSettingsRoute: typeof AuthAppSettingsRoute
}

const AuthAppRouteRouteChildren: AuthAppRouteRouteChildren = {
  AuthAppDashboardRoute: AuthAppDashboardRoute,
  AuthAppSettingsRoute: AuthAppSettingsRoute,
}

const AuthAppRouteRouteWithChildren = AuthAppRouteRoute._addFileChildren(
  AuthAppRouteRouteChildren,
)

interface AuthBlogRouteRouteChildren {
  AuthBlogCreateRoute: typeof AuthBlogCreateRoute
  AuthBlogIndexRoute: typeof AuthBlogIndexRoute
  AuthBlogPostIdModalRoute: typeof AuthBlogPostIdModalRoute
  AuthBlogPostPostIdEditRoute: typeof AuthBlogPostPostIdEditRoute
  AuthBlogPostPostIdViewRoute: typeof AuthBlogPostPostIdViewRoute
}

const AuthBlogRouteRouteChildren: AuthBlogRouteRouteChildren = {
  AuthBlogCreateRoute: AuthBlogCreateRoute,
  AuthBlogIndexRoute: AuthBlogIndexRoute,
  AuthBlogPostIdModalRoute: AuthBlogPostIdModalRoute,
  AuthBlogPostPostIdEditRoute: AuthBlogPostPostIdEditRoute,
  AuthBlogPostPostIdViewRoute: AuthBlogPostPostIdViewRoute,
}

const AuthBlogRouteRouteWithChildren = AuthBlogRouteRoute._addFileChildren(
  AuthBlogRouteRouteChildren,
)

interface AuthDocumentsRouteRouteChildren {
  AuthDocumentsIndexRoute: typeof AuthDocumentsIndexRoute
  AuthDocumentsCategoryCategoryIdRoute: typeof AuthDocumentsCategoryCategoryIdRoute
  AuthDocumentsDocumentIdIndexRoute: typeof AuthDocumentsDocumentIdIndexRoute
}

const AuthDocumentsRouteRouteChildren: AuthDocumentsRouteRouteChildren = {
  AuthDocumentsIndexRoute: AuthDocumentsIndexRoute,
  AuthDocumentsCategoryCategoryIdRoute: AuthDocumentsCategoryCategoryIdRoute,
  AuthDocumentsDocumentIdIndexRoute: AuthDocumentsDocumentIdIndexRoute,
}

const AuthDocumentsRouteRouteWithChildren =
  AuthDocumentsRouteRoute._addFileChildren(AuthDocumentsRouteRouteChildren)

interface AuthSettingsRouteRouteChildren {
  AuthSettingsNotificationsRoute: typeof AuthSettingsNotificationsRoute
  AuthSettingsProfileRoute: typeof AuthSettingsProfileRoute
}

const AuthSettingsRouteRouteChildren: AuthSettingsRouteRouteChildren = {
  AuthSettingsNotificationsRoute: AuthSettingsNotificationsRoute,
  AuthSettingsProfileRoute: AuthSettingsProfileRoute,
}

const AuthSettingsRouteRouteWithChildren =
  AuthSettingsRouteRoute._addFileChildren(AuthSettingsRouteRouteChildren)

interface AuthPathlessLayoutRouteChildren {
  AuthPathlessLayoutARoute: typeof AuthPathlessLayoutARoute
  AuthPathlessLayoutBRoute: typeof AuthPathlessLayoutBRoute
}

const AuthPathlessLayoutRouteChildren: AuthPathlessLayoutRouteChildren = {
  AuthPathlessLayoutARoute: AuthPathlessLayoutARoute,
  AuthPathlessLayoutBRoute: AuthPathlessLayoutBRoute,
}

const AuthPathlessLayoutRouteWithChildren =
  AuthPathlessLayoutRoute._addFileChildren(AuthPathlessLayoutRouteChildren)

interface AuthPostsRouteChildren {
  AuthPostsPostIdRoute: typeof AuthPostsPostIdRoute
  AuthPostsIndexRoute: typeof AuthPostsIndexRoute
  AuthPostsEditPostIdRoute: typeof AuthPostsEditPostIdRoute
}

const AuthPostsRouteChildren: AuthPostsRouteChildren = {
  AuthPostsPostIdRoute: AuthPostsPostIdRoute,
  AuthPostsIndexRoute: AuthPostsIndexRoute,
  AuthPostsEditPostIdRoute: AuthPostsEditPostIdRoute,
}

const AuthPostsRouteWithChildren = AuthPostsRoute._addFileChildren(
  AuthPostsRouteChildren,
)

interface AuthRouteChildren {
  AuthAppRouteRoute: typeof AuthAppRouteRouteWithChildren
  AuthBlogRouteRoute: typeof AuthBlogRouteRouteWithChildren
  AuthDocumentsRouteRoute: typeof AuthDocumentsRouteRouteWithChildren
  AuthSettingsRouteRoute: typeof AuthSettingsRouteRouteWithChildren
  AuthPathlessLayoutRoute: typeof AuthPathlessLayoutRouteWithChildren
  AuthAboutRoute: typeof AuthAboutRoute
  AuthContactsRoute: typeof AuthContactsRoute
  AuthFaqRoute: typeof AuthFaqRoute
  AuthPostsRoute: typeof AuthPostsRouteWithChildren
  AuthServicesRoute: typeof AuthServicesRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAppRouteRoute: AuthAppRouteRouteWithChildren,
  AuthBlogRouteRoute: AuthBlogRouteRouteWithChildren,
  AuthDocumentsRouteRoute: AuthDocumentsRouteRouteWithChildren,
  AuthSettingsRouteRoute: AuthSettingsRouteRouteWithChildren,
  AuthPathlessLayoutRoute: AuthPathlessLayoutRouteWithChildren,
  AuthAboutRoute: AuthAboutRoute,
  AuthContactsRoute: AuthContactsRoute,
  AuthFaqRoute: AuthFaqRoute,
  AuthPostsRoute: AuthPostsRouteWithChildren,
  AuthServicesRoute: AuthServicesRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ErrorsRouteChildren {
  Errors404Route: typeof Errors404Route
  Errors500Route: typeof Errors500Route
}

const ErrorsRouteChildren: ErrorsRouteChildren = {
  Errors404Route: Errors404Route,
  Errors500Route: Errors500Route,
}

const ErrorsRouteWithChildren =
  ErrorsRoute._addFileChildren(ErrorsRouteChildren)

interface UnsignedRouteChildren {
  UnsignedLoginRoute: typeof UnsignedLoginRoute
}

const UnsignedRouteChildren: UnsignedRouteChildren = {
  UnsignedLoginRoute: UnsignedLoginRoute,
}

const UnsignedRouteWithChildren = UnsignedRoute._addFileChildren(
  UnsignedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ErrorsRoute: ErrorsRouteWithChildren,
  UnsignedRoute: UnsignedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
