/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio";
import { getCommentsByDocumentIdHandler } from "./CommentsHandlers/getCommentsByDocumentId.ts";
import { createDocumentCategoryV1Handler } from "./DocumentsHandlers/createDocumentCategoryV1.ts";
import { getAllDocCategoriesV1Handler } from "./DocumentsHandlers/getAllDocCategoriesV1.ts";
import { getDocumentByIdHandler } from "./DocumentsHandlers/getDocumentById.ts";
import { getDocumentsCategoryByIdHandler } from "./DocumentsHandlers/getDocumentsCategoryById.ts";
import { removeDocumentCategoryByIdHandler } from "./DocumentsHandlers/removeDocumentCategoryById.ts";
import { updateDocumentCategoryByIdHandler } from "./DocumentsHandlers/updateDocumentCategoryById.ts";
import { getCommentsByDocumentIdQueryResponseSchema } from "../zod/comments-schema/get-comments-by-document-id-schema.ts";
import {
  createDocumentCategoryV1MutationRequestSchema,
  createDocumentCategoryV1MutationResponseSchema,
} from "../zod/documents-schema/create-document-category-v1schema.ts";
import { getAllDocCategoriesV1QueryResponseSchema } from "../zod/documents-schema/get-all-doc-categories-v1schema.ts";
import { getDocumentByIdQueryResponseSchema } from "../zod/documents-schema/get-document-by-id-schema.ts";
import {
  getDocumentsCategoryByIdQueryParamsSchema,
  getDocumentsCategoryByIdQueryResponseSchema,
} from "../zod/documents-schema/get-documents-category-by-id-schema.ts";
import { removeDocumentCategoryByIdMutationResponseSchema } from "../zod/documents-schema/remove-document-category-by-id-schema.ts";
import {
  updateDocumentCategoryByIdMutationRequestSchema,
  updateDocumentCategoryByIdMutationResponseSchema,
} from "../zod/documents-schema/update-document-category-by-id-schema.ts";
import { z } from "zod";

export const server = new McpServer({
  name: "Documents API",
  version: "3.0.0",
});

server.registerTool(
  "getAllDocCategoriesV1",
  {
    title: "Список категорий документов",
    description: "Получение списка всех категорий документов",
    outputSchema: { data: getAllDocCategoriesV1QueryResponseSchema },
  },
  async () => {
    return getAllDocCategoriesV1Handler();
  },
);

server.registerTool(
  "createDocumentCategoryV1",
  {
    title: "Создание категории документов",
    description: "Создание новой категории документов",
    outputSchema: { data: createDocumentCategoryV1MutationResponseSchema },
    inputSchema: { data: createDocumentCategoryV1MutationRequestSchema },
  },
  async ({ data }) => {
    return createDocumentCategoryV1Handler({ data });
  },
);

server.registerTool(
  "getDocumentsCategoryById",
  {
    title: "Получение категории документов по ID",
    description:
      "Получение категории документов по ID и краткого списка документов",
    outputSchema: { data: getDocumentsCategoryByIdQueryResponseSchema },
    inputSchema: {
      categoryId: z.coerce.number(),
      params: getDocumentsCategoryByIdQueryParamsSchema,
    },
  },
  async ({ categoryId, params }) => {
    return getDocumentsCategoryByIdHandler({ categoryId, params });
  },
);

server.registerTool(
  "updateDocumentCategoryById",
  {
    title: "Обновление категории документа",
    description: "Обновление категории документа по ID",
    outputSchema: { data: updateDocumentCategoryByIdMutationResponseSchema },
    inputSchema: {
      categoryId: z.coerce.number(),
      data: updateDocumentCategoryByIdMutationRequestSchema,
    },
  },
  async ({ categoryId, data }) => {
    return updateDocumentCategoryByIdHandler({ categoryId, data });
  },
);

server.registerTool(
  "removeDocumentCategoryById",
  {
    title: "Удаление категории документов",
    description: "Удаление категории документов по ID",
    outputSchema: { data: removeDocumentCategoryByIdMutationResponseSchema },
    inputSchema: { categoryId: z.coerce.number() },
  },
  async ({ categoryId }) => {
    return removeDocumentCategoryByIdHandler({ categoryId });
  },
);

server.registerTool(
  "getDocumentById",
  {
    title: "Получение категории документов по ID",
    description:
      "Получение категории документов по ID и краткого списка документов",
    outputSchema: { data: getDocumentByIdQueryResponseSchema },
    inputSchema: { documentId: z.coerce.number() },
  },
  async ({ documentId }) => {
    return getDocumentByIdHandler({ documentId });
  },
);

server.registerTool(
  "getCommentsByDocumentId",
  {
    title: "Комментарии документа",
    description: "Получение комментариев к документу",
    outputSchema: { data: getCommentsByDocumentIdQueryResponseSchema },
    inputSchema: { documentId: z.coerce.number() },
  },
  async ({ documentId }) => {
    return getCommentsByDocumentIdHandler({ documentId });
  },
);

export async function startServer() {
  try {
    const transport = new StdioServerTransport();
    await server.connect(transport);
  } catch (error) {
    console.error("Failed to start server:", error);
    process.exit(1);
  }
}
