/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentCategoryRequestV1Schema } from "../document-category-request-v1schema.ts";
import { documentCategoryResponseV1Schema } from "../document-category-response-v1schema.ts";

/**
 * @description Успешный запрос
 */
export const createDocumentCategoryV1201Schema = z
  .lazy(() => documentCategoryResponseV1Schema)
  .describe("Информация о категории");

export type CreateDocumentCategoryV1201Schema = z.infer<
  typeof createDocumentCategoryV1201Schema
>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const createDocumentCategoryV1400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type CreateDocumentCategoryV1400Schema = z.infer<
  typeof createDocumentCategoryV1400Schema
>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const createDocumentCategoryV1401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type CreateDocumentCategoryV1401Schema = z.infer<
  typeof createDocumentCategoryV1401Schema
>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const createDocumentCategoryV1403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type CreateDocumentCategoryV1403Schema = z.infer<
  typeof createDocumentCategoryV1403Schema
>;

/**
 * @description Ошибка сервера
 */
export const createDocumentCategoryV1500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type CreateDocumentCategoryV1500Schema = z.infer<
  typeof createDocumentCategoryV1500Schema
>;

export const createDocumentCategoryV1MutationRequestSchema = z
  .lazy(() => documentCategoryRequestV1Schema)
  .describe("Модель создания / обновления категории документов");

export type CreateDocumentCategoryV1MutationRequestSchema = z.infer<
  typeof createDocumentCategoryV1MutationRequestSchema
>;

export const createDocumentCategoryV1MutationResponseSchema = z.lazy(
  () => createDocumentCategoryV1201Schema,
);

export type CreateDocumentCategoryV1MutationResponseSchema = z.infer<
  typeof createDocumentCategoryV1MutationResponseSchema
>;
