/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentCategoryListResponseV1Schema } from "../document-category-list-response-v1schema.ts";

/**
 * @description Успешный запрос
 */
export const getAllDocCategoriesV1200Schema = z
  .lazy(() => documentCategoryListResponseV1Schema)
  .describe("Модель ответа - Список категорий документов");

export type GetAllDocCategoriesV1200Schema = z.infer<
  typeof getAllDocCategoriesV1200Schema
>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const getAllDocCategoriesV1400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetAllDocCategoriesV1400Schema = z.infer<
  typeof getAllDocCategoriesV1400Schema
>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const getAllDocCategoriesV1401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetAllDocCategoriesV1401Schema = z.infer<
  typeof getAllDocCategoriesV1401Schema
>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const getAllDocCategoriesV1403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetAllDocCategoriesV1403Schema = z.infer<
  typeof getAllDocCategoriesV1403Schema
>;

/**
 * @description Ошибка сервера
 */
export const getAllDocCategoriesV1500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetAllDocCategoriesV1500Schema = z.infer<
  typeof getAllDocCategoriesV1500Schema
>;

export const getAllDocCategoriesV1QueryResponseSchema = z.lazy(
  () => getAllDocCategoriesV1200Schema,
);

export type GetAllDocCategoriesV1QueryResponseSchema = z.infer<
  typeof getAllDocCategoriesV1QueryResponseSchema
>;
