/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentResponseV1Schema } from "../document-response-v1schema.ts";

export const getDocumentByIdPathParamsSchema = z.object({
  documentId: z.coerce.number().int().min(1).describe("ID документа"),
});

export type GetDocumentByIdPathParamsSchema = z.infer<
  typeof getDocumentByIdPathParamsSchema
>;

/**
 * @description Успешный запрос
 */
export const getDocumentById200Schema = z.lazy(() => documentResponseV1Schema);

export type GetDocumentById200Schema = z.infer<typeof getDocumentById200Schema>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const getDocumentById400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentById400Schema = z.infer<typeof getDocumentById400Schema>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const getDocumentById401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentById401Schema = z.infer<typeof getDocumentById401Schema>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const getDocumentById403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentById403Schema = z.infer<typeof getDocumentById403Schema>;

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export const getDocumentById404Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentById404Schema = z.infer<typeof getDocumentById404Schema>;

/**
 * @description Ошибка сервера
 */
export const getDocumentById500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentById500Schema = z.infer<typeof getDocumentById500Schema>;

export const getDocumentByIdQueryResponseSchema = z.lazy(
  () => getDocumentById200Schema,
);

export type GetDocumentByIdQueryResponseSchema = z.infer<
  typeof getDocumentByIdQueryResponseSchema
>;
