/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentCategoryResponseV1Schema } from "../document-category-response-v1schema.ts";

export const getDocumentsCategoryByIdPathParamsSchema = z.object({
  categoryId: z.uuid().min(1).describe("ID категории документов"),
});

export type GetDocumentsCategoryByIdPathParamsSchema = z.infer<
  typeof getDocumentsCategoryByIdPathParamsSchema
>;

export const getDocumentsCategoryByIdQueryParamsSchema = z.object({
  page: z.coerce.number().int().min(1).default(1).describe("Номер страницы"),
  size: z.coerce
    .number()
    .int()
    .min(1)
    .default(10)
    .describe("По сколько элементов выводить на страницу"),
  sort: z.optional(
    z
      .array(z.string())
      .refine((items) => new Set(items).size === items.length, {
        message: "Array entries must be unique",
      })
      .describe("Направление сортировки. Например `name,desc`"),
  ),
});

export type GetDocumentsCategoryByIdQueryParamsSchema = z.infer<
  typeof getDocumentsCategoryByIdQueryParamsSchema
>;

/**
 * @description Успешный запрос
 */
export const getDocumentsCategoryById200Schema = z
  .lazy(() => documentCategoryResponseV1Schema)
  .describe("Информация о категории");

export type GetDocumentsCategoryById200Schema = z.infer<
  typeof getDocumentsCategoryById200Schema
>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const getDocumentsCategoryById400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentsCategoryById400Schema = z.infer<
  typeof getDocumentsCategoryById400Schema
>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const getDocumentsCategoryById401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentsCategoryById401Schema = z.infer<
  typeof getDocumentsCategoryById401Schema
>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const getDocumentsCategoryById403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentsCategoryById403Schema = z.infer<
  typeof getDocumentsCategoryById403Schema
>;

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export const getDocumentsCategoryById404Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentsCategoryById404Schema = z.infer<
  typeof getDocumentsCategoryById404Schema
>;

/**
 * @description Ошибка сервера
 */
export const getDocumentsCategoryById500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetDocumentsCategoryById500Schema = z.infer<
  typeof getDocumentsCategoryById500Schema
>;

export const getDocumentsCategoryByIdQueryResponseSchema = z.lazy(
  () => getDocumentsCategoryById200Schema,
);

export type GetDocumentsCategoryByIdQueryResponseSchema = z.infer<
  typeof getDocumentsCategoryByIdQueryResponseSchema
>;
