/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

export const removeDocumentCategoryByIdPathParamsSchema = z.object({
  categoryId: z.coerce
    .number()
    .int()
    .min(1)
    .describe("ID категории документов"),
});

export type RemoveDocumentCategoryByIdPathParamsSchema = z.infer<
  typeof removeDocumentCategoryByIdPathParamsSchema
>;

/**
 * @description Успешный запрос
 */
export const removeDocumentCategoryById204Schema = z.unknown();

export type RemoveDocumentCategoryById204Schema = z.infer<
  typeof removeDocumentCategoryById204Schema
>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const removeDocumentCategoryById400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type RemoveDocumentCategoryById400Schema = z.infer<
  typeof removeDocumentCategoryById400Schema
>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const removeDocumentCategoryById401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type RemoveDocumentCategoryById401Schema = z.infer<
  typeof removeDocumentCategoryById401Schema
>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const removeDocumentCategoryById403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type RemoveDocumentCategoryById403Schema = z.infer<
  typeof removeDocumentCategoryById403Schema
>;

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export const removeDocumentCategoryById404Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type RemoveDocumentCategoryById404Schema = z.infer<
  typeof removeDocumentCategoryById404Schema
>;

/**
 * @description Ошибка сервера
 */
export const removeDocumentCategoryById500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type RemoveDocumentCategoryById500Schema = z.infer<
  typeof removeDocumentCategoryById500Schema
>;

export const removeDocumentCategoryByIdMutationResponseSchema = z.lazy(
  () => removeDocumentCategoryById204Schema,
);

export type RemoveDocumentCategoryByIdMutationResponseSchema = z.infer<
  typeof removeDocumentCategoryByIdMutationResponseSchema
>;
