/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentCategoryRequestV1Schema } from "../document-category-request-v1schema.ts";
import { documentCategoryResponseV1Schema } from "../document-category-response-v1schema.ts";

export const updateDocumentCategoryByIdPathParamsSchema = z.object({
  categoryId: z.coerce
    .number()
    .int()
    .min(1)
    .describe("ID категории документов"),
});

export type UpdateDocumentCategoryByIdPathParamsSchema = z.infer<
  typeof updateDocumentCategoryByIdPathParamsSchema
>;

/**
 * @description Успешный запрос
 */
export const updateDocumentCategoryById200Schema = z
  .lazy(() => documentCategoryResponseV1Schema)
  .describe("Информация о категории");

export type UpdateDocumentCategoryById200Schema = z.infer<
  typeof updateDocumentCategoryById200Schema
>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const updateDocumentCategoryById400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type UpdateDocumentCategoryById400Schema = z.infer<
  typeof updateDocumentCategoryById400Schema
>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const updateDocumentCategoryById401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type UpdateDocumentCategoryById401Schema = z.infer<
  typeof updateDocumentCategoryById401Schema
>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const updateDocumentCategoryById403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type UpdateDocumentCategoryById403Schema = z.infer<
  typeof updateDocumentCategoryById403Schema
>;

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export const updateDocumentCategoryById404Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type UpdateDocumentCategoryById404Schema = z.infer<
  typeof updateDocumentCategoryById404Schema
>;

/**
 * @description Ошибка сервера
 */
export const updateDocumentCategoryById500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type UpdateDocumentCategoryById500Schema = z.infer<
  typeof updateDocumentCategoryById500Schema
>;

export const updateDocumentCategoryByIdMutationRequestSchema = z
  .lazy(() => documentCategoryRequestV1Schema)
  .describe("Модель создания / обновления категории документов");

export type UpdateDocumentCategoryByIdMutationRequestSchema = z.infer<
  typeof updateDocumentCategoryByIdMutationRequestSchema
>;

export const updateDocumentCategoryByIdMutationResponseSchema = z.lazy(
  () => updateDocumentCategoryById200Schema,
);

export type UpdateDocumentCategoryByIdMutationResponseSchema = z.infer<
  typeof updateDocumentCategoryByIdMutationResponseSchema
>;
