// @ts-nocheck

/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/api/client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/api/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetCommentsByDocumentIdQueryResponse,
  GetCommentsByDocumentIdPathParams,
  GetCommentsByDocumentId400,
  GetCommentsByDocumentId401,
  GetCommentsByDocumentId403,
  GetCommentsByDocumentId404,
  GetCommentsByDocumentId500,
} from "../../../types/get-comments-by-document-id.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getCommentsByDocumentIdQueryResponseSchema } from "../../../zod/comments-schema/get-comments-by-document-id-schema.ts";

export const getCommentsByDocumentIdQueryKey = (
  documentId: GetCommentsByDocumentIdPathParams["documentId"] | undefined,
) =>
  [
    {
      url: "/v1/documents/:documentId/comments",
      params: { documentId: documentId },
    },
  ] as const;

export type GetCommentsByDocumentIdQueryKey = ReturnType<
  typeof getCommentsByDocumentIdQueryKey
>;

/**
 * @description Получение комментариев к документу
 * @summary Комментарии документа
 * {@link /v1/documents/:documentId/comments}
 */
export async function getCommentsByDocumentId(
  documentId: GetCommentsByDocumentIdPathParams["documentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetCommentsByDocumentIdQueryResponse,
    ResponseErrorConfig<
      | GetCommentsByDocumentId400
      | GetCommentsByDocumentId401
      | GetCommentsByDocumentId403
      | GetCommentsByDocumentId404
      | GetCommentsByDocumentId500
    >,
    unknown
  >({
    method: "GET",
    url: `/v1/documents/${documentId}/comments`,
    baseURL: `/`,
    ...requestConfig,
  });
  return getCommentsByDocumentIdQueryResponseSchema.parse(res.data);
}

export function getCommentsByDocumentIdQueryOptions(
  documentId: GetCommentsByDocumentIdPathParams["documentId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getCommentsByDocumentIdQueryKey(documentId);
  return queryOptions<
    GetCommentsByDocumentIdQueryResponse,
    ResponseErrorConfig<
      | GetCommentsByDocumentId400
      | GetCommentsByDocumentId401
      | GetCommentsByDocumentId403
      | GetCommentsByDocumentId404
      | GetCommentsByDocumentId500
    >,
    GetCommentsByDocumentIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!documentId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getCommentsByDocumentId(documentId!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Получение комментариев к документу
 * @summary Комментарии документа
 * {@link /v1/documents/:documentId/comments}
 */
export function useGetCommentsByDocumentId<
  TData = GetCommentsByDocumentIdQueryResponse,
  TQueryData = GetCommentsByDocumentIdQueryResponse,
  TQueryKey extends QueryKey = GetCommentsByDocumentIdQueryKey,
>(
  documentId: GetCommentsByDocumentIdPathParams["documentId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetCommentsByDocumentIdQueryResponse,
        ResponseErrorConfig<
          | GetCommentsByDocumentId400
          | GetCommentsByDocumentId401
          | GetCommentsByDocumentId403
          | GetCommentsByDocumentId404
          | GetCommentsByDocumentId500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getCommentsByDocumentIdQueryKey(documentId);

  const query = useQuery(
    {
      ...getCommentsByDocumentIdQueryOptions(documentId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetCommentsByDocumentId400
      | GetCommentsByDocumentId401
      | GetCommentsByDocumentId403
      | GetCommentsByDocumentId404
      | GetCommentsByDocumentId500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
