/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ForbiddenError } from "../types/forbidden-error.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель ошибки, приходящей с сервера
 */
export function createForbiddenError(
  data?: Partial<ForbiddenError>,
): ForbiddenError {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}
