/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommentDtoV1 } from "../types/comment-dto-v1.ts";
import { faker } from "@faker-js/faker";
import { createUserMetaDataDtoV1 } from "./createUserMetaDataDtoV1.ts";

/**
 * @description Модель комментария
 */
export function createCommentDtoV1(data?: Partial<CommentDtoV1>): CommentDtoV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int({ min: 1 }),
      text: faker.string.alpha(),
      createdAt: faker.date.anytime().toISOString(),
      get author() {
        return createUserMetaDataDtoV1();
      },
      children: faker.helpers.multiple(() => undefined as any),
      ...(data || {}),
    },
  };
}
