/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryV1 } from "../types/document-category-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Список категорий
 */
export function createDocumentCategoryV1(
  data?: Partial<DocumentCategoryV1>,
): DocumentCategoryV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.string.uuid(),
      title: faker.string.alpha(),
      countDocuments: faker.number.int({ min: 0 }),
    },
    ...(data || {}),
  };
}
