/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentBlockImageV1 } from "../types/document-block-image-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Блок документа - Картинка
 */
export function createDocumentBlockImageV1(
  data?: Partial<DocumentBlockImageV1>,
): DocumentBlockImageV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int(),
      type: faker.helpers.arrayElement<
        NonNullable<DocumentBlockImageV1>["type"]
      >(["image"]),
      position: faker.number.int({ min: 1 }),
      settings: {
        title: faker.string.alpha(),
        src: faker.internet.url(),
        width: faker.number.int({ min: 0 }),
        height: faker.number.int({ min: 0 }),
      },
    },
    ...(data || {}),
  };
}
