/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { InternalServerError } from "../types/internal-server-error.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель ошибки, приходящей с сервера
 */
export function createInternalServerError(
  data?: Partial<InternalServerError>,
): InternalServerError {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}
