/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { NotFoundError } from "../types/not-found-error.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель ошибки, приходящей с сервера
 */
export function createNotFoundError(
  data?: Partial<NotFoundError>,
): NotFoundError {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}
