/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryResponseV1 } from "../types/document-category-response-v1.ts";
import { faker } from "@faker-js/faker";
import { createDocumentCategoryV1 } from "./createDocumentCategoryV1.ts";
import { createDocumentMetaDtoV1 } from "./createDocumentMetaDtoV1.ts";
import { createPaginationMetaV1 } from "./createPaginationMetaV1.ts";

/**
 * @description Информация о категории
 */
export function createDocumentCategoryResponseV1(
  data?: Partial<DocumentCategoryResponseV1>,
): DocumentCategoryResponseV1 {
  faker.seed([100]);
  return {
    ...{
      get category() {
        return createDocumentCategoryV1();
      },
      get pageInfo() {
        return createPaginationMetaV1();
      },
      get documents() {
        return faker.helpers.multiple(() => createDocumentMetaDtoV1());
      },
      ...(data || {}),
    },
  };
}
