/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentMetaDtoV1 } from "../types/document-meta-dto-v1.ts";
import { faker } from "@faker-js/faker";
import { createDocumentTypeEnumV1 } from "./createDocumentTypeEnumV1.ts";
import { createUserMetaDataDtoV1 } from "./createUserMetaDataDtoV1.ts";

/**
 * @description Базовая модель документа
 */
export function createDocumentMetaDtoV1(
  data?: Partial<DocumentMetaDtoV1>,
): DocumentMetaDtoV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int(),
      title: faker.string.alpha(),
      description: faker.string.alpha(),
      createdAt: faker.date.anytime().toISOString(),
      updatedAt: faker.date.anytime().toISOString(),
      comments: faker.number.int({ min: 0 }),
      get createdBy() {
        return createUserMetaDataDtoV1();
      },
      get type() {
        return createDocumentTypeEnumV1();
      },
      ...(data || {}),
    },
  };
}
