/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryRequestV1 } from "../types/document-category-request-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель создания / обновления категории документов
 */
export function createDocumentCategoryRequestV1(
  data?: Partial<DocumentCategoryRequestV1>,
): DocumentCategoryRequestV1 {
  faker.seed([100]);
  return {
    ...{ title: faker.string.alpha() },
    ...(data || {}),
  };
}
