/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentBlockParagraphV1 } from "../types/document-block-paragraph-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Блок документа - Параграф
 */
export function createDocumentBlockParagraphV1(
  data?: Partial<DocumentBlockParagraphV1>,
): DocumentBlockParagraphV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int(),
      type: faker.helpers.arrayElement<
        NonNullable<DocumentBlockParagraphV1>["type"]
      >(["paragraph"]),
      position: faker.number.int({ min: 1 }),
      value: faker.string.alpha(),
    },
    ...(data || {}),
  };
}
