/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UnauthorizedError } from "../types/unauthorized-error.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель ошибки, приходящей с сервера
 */
export function createUnauthorizedError(
  data?: Partial<UnauthorizedError>,
): UnauthorizedError {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}
