/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PaginationMetaV1 } from "../types/pagination-meta-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель пагинации
 */
export function createPaginationMetaV1(
  data?: Partial<PaginationMetaV1>,
): PaginationMetaV1 {
  faker.seed([100]);
  return {
    ...{
      empty: faker.datatype.boolean(),
      first: faker.datatype.boolean(),
      last: faker.datatype.boolean(),
      number: faker.number.int({ min: 0 }),
      numberOfElements: faker.number.int({ min: 0 }),
      size: faker.number.int({ min: 0 }),
      totalElements: faker.number.int({ min: 0 }),
      totalPages: faker.number.int({ min: 1 }),
      sort: {
        empty: faker.datatype.boolean(),
        sorted: faker.datatype.boolean(),
        unsorted: faker.datatype.boolean(),
      },
      pageable: {
        offset: faker.number.int({ min: 0 }),
        pageNumber: faker.number.int({ min: 0 }),
        pageSize: faker.number.int({ min: 0 }),
        paged: faker.datatype.boolean(),
        unpaged: faker.datatype.boolean(),
        sort: {
          empty: faker.datatype.boolean(),
          sorted: faker.datatype.boolean(),
          unsorted: faker.datatype.boolean(),
        },
      },
    },
    ...(data || {}),
  };
}
