/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { BadRequestError } from "../types/bad-request-error.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Модель ошибки, приходящей с сервера
 */
export function createBadRequestError(
  data?: Partial<BadRequestError>,
): BadRequestError {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}
