/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentBlockTitleV1 } from "../types/document-block-title-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Блок документа - Заголовок
 */
export function createDocumentBlockTitleV1(
  data?: Partial<DocumentBlockTitleV1>,
): DocumentBlockTitleV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int(),
      type: faker.helpers.arrayElement<
        NonNullable<DocumentBlockTitleV1>["type"]
      >(["header"]),
      level: faker.helpers.arrayElement<
        NonNullable<DocumentBlockTitleV1>["level"]
      >(["1", "2", "3", "4", "5", "6"]),
      position: faker.number.int({ min: 1 }),
      value: faker.string.alpha(),
    },
    ...(data || {}),
  };
}
