/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentResponseV1 } from "../types/document-response-v1.ts";
import { faker } from "@faker-js/faker";
import { createDocumentBlockImageV1 } from "./createDocumentBlockImageV1.ts";
import { createDocumentBlockParagraphV1 } from "./createDocumentBlockParagraphV1.ts";
import { createDocumentBlockTitleV1 } from "./createDocumentBlockTitleV1.ts";
import { createDocumentCategoryV1 } from "./createDocumentCategoryV1.ts";
import { createDocumentMetaDtoV1 } from "./createDocumentMetaDtoV1.ts";

export function createDocumentResponseV1(
  data?: Partial<DocumentResponseV1>,
): DocumentResponseV1 {
  faker.seed([100]);
  return {
    ...{
      ...createDocumentMetaDtoV1(),
      ...{
        get content() {
          return faker.helpers.multiple(() =>
            faker.helpers.arrayElement<any>([
              createDocumentBlockTitleV1(),
              createDocumentBlockParagraphV1(),
              createDocumentBlockImageV1(),
            ]),
          );
        },
        get category() {
          return createDocumentCategoryV1();
        },
      },
    },
    ...(data || {}),
  };
}
