/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UserMetaDataDtoV1 } from "../types/user-meta-data-dto-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Ограниченные данные о пользователе
 */
export function createUserMetaDataDtoV1(
  data?: Partial<UserMetaDataDtoV1>,
): UserMetaDataDtoV1 {
  faker.seed([100]);
  return {
    ...{
      id: faker.number.int(),
      firstName: faker.string.alpha({ length: { min: 3, max: 50 } }),
      lastName: faker.string.alpha({ length: { min: 2, max: 50 } }),
      avatarUrl: faker.internet.url(),
    },
    ...(data || {}),
  };
}
