/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentCategoryListResponseV1 } from "../types/document-category-list-response-v1.ts";
import { faker } from "@faker-js/faker";
import { createDocumentCategoryV1 } from "./createDocumentCategoryV1.ts";
import { createPaginationMetaV1 } from "./createPaginationMetaV1.ts";

/**
 * @description Модель ответа - Список категорий документов
 */
export function createDocumentCategoryListResponseV1(
  data?: Partial<DocumentCategoryListResponseV1>,
): DocumentCategoryListResponseV1 {
  faker.seed([100]);
  return {
    ...{
      ...createPaginationMetaV1(),
      ...{
        get content() {
          return faker.helpers.multiple(() => createDocumentCategoryV1());
        },
      },
    },
    ...(data || {}),
  };
}
