/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CommentsListDtoV1 } from "../types/comments-list-dto-v1.ts";
import { faker } from "@faker-js/faker";
import { createCommentDtoV1 } from "./createCommentDtoV1.ts";

/**
 * @description Список комментариев документа
 */
export function createCommentsListDtoV1(
  data?: CommentsListDtoV1,
): CommentsListDtoV1 {
  faker.seed([100]);
  return [
    ...faker.helpers.multiple(() => createCommentDtoV1()),
    ...(data || []),
  ];
}
