/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DocumentTypeEnumV1 } from "../types/document-type-enum-v1.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Тип документа
 */
export function createDocumentTypeEnumV1(
  data?: Partial<DocumentTypeEnumV1>,
): DocumentTypeEnumV1 {
  faker.seed([100]);
  return (
    data ||
    faker.helpers.arrayElement<DocumentTypeEnumV1>(["PUBLIC", "PRIVATE"])
  );
}
