/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { commentsListDtoV1Schema } from "../comments-list-dto-v1schema.ts";

export const getCommentsByDocumentIdPathParamsSchema = z.object({
  documentId: z.coerce.number().int().min(1).describe("ID документа"),
});

export type GetCommentsByDocumentIdPathParamsSchema = z.infer<
  typeof getCommentsByDocumentIdPathParamsSchema
>;

/**
 * @description Успешный запрос
 */
export const getCommentsByDocumentId200Schema = z
  .lazy(() => commentsListDtoV1Schema)
  .describe("Список комментариев документа");

export type GetCommentsByDocumentId200Schema = z.infer<
  typeof getCommentsByDocumentId200Schema
>;

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export const getCommentsByDocumentId400Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetCommentsByDocumentId400Schema = z.infer<
  typeof getCommentsByDocumentId400Schema
>;

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export const getCommentsByDocumentId401Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetCommentsByDocumentId401Schema = z.infer<
  typeof getCommentsByDocumentId401Schema
>;

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export const getCommentsByDocumentId403Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetCommentsByDocumentId403Schema = z.infer<
  typeof getCommentsByDocumentId403Schema
>;

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export const getCommentsByDocumentId404Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetCommentsByDocumentId404Schema = z.infer<
  typeof getCommentsByDocumentId404Schema
>;

/**
 * @description Ошибка сервера
 */
export const getCommentsByDocumentId500Schema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type GetCommentsByDocumentId500Schema = z.infer<
  typeof getCommentsByDocumentId500Schema
>;

export const getCommentsByDocumentIdQueryResponseSchema = z.lazy(
  () => getCommentsByDocumentId200Schema,
);

export type GetCommentsByDocumentIdQueryResponseSchema = z.infer<
  typeof getCommentsByDocumentIdQueryResponseSchema
>;
