/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Модель ошибки, приходящей с сервера
 */
export const badRequestErrorSchema = z
  .object({
    message: z.string().describe("Текст ошибки"),
  })
  .describe("Модель ошибки, приходящей с сервера");

export type BadRequestErrorSchema = z.infer<typeof badRequestErrorSchema>;
