/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { commentDtoV1Schema } from "./comment-dto-v1schema.ts";

/**
 * @description Список комментариев документа
 */
export const commentsListDtoV1Schema = z
  .array(z.lazy(() => commentDtoV1Schema).describe("Модель комментария"))
  .describe("Список комментариев документа");

export type CommentsListDtoV1Schema = z.infer<typeof commentsListDtoV1Schema>;
