/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { userMetaDataDtoV1Schema } from "./user-meta-data-dto-v1schema.ts";

/**
 * @description Модель комментария
 */
export const commentDtoV1Schema = z
  .object({
    id: z.int().min(1).describe("ID комментария"),
    text: z.string().describe("Текст комментария"),
    createdAt: z.iso.datetime({ offset: true }).describe("Дата создания"),
    get author() {
      return userMetaDataDtoV1Schema.describe(
        "Ограниченные данные о пользователе",
      );
    },
    get children() {
      return z
        .array(commentDtoV1Schema.describe("Модель комментария"))
        .describe("Список дочерних комментариев");
    },
  })
  .describe("Модель комментария");

export type CommentDtoV1Schema = z.infer<typeof commentDtoV1Schema>;
