/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentCategoryV1Schema } from "./document-category-v1schema.ts";
import { paginationMetaV1Schema } from "./pagination-meta-v1schema.ts";

/**
 * @description Модель ответа - Список категорий документов
 */
export const documentCategoryListResponseV1Schema = z
  .lazy(() => paginationMetaV1Schema)
  .and(
    z.object({
      get content() {
        return z
          .array(documentCategoryV1Schema.describe("Список категорий"))
          .describe("Список категорий")
          .optional();
      },
    }),
  )
  .describe("Модель ответа - Список категорий документов");

export type DocumentCategoryListResponseV1Schema = z.infer<
  typeof documentCategoryListResponseV1Schema
>;
