/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Блок документа - Параграф
 */
export const documentBlockParagraphV1Schema = z
  .object({
    id: z.int().describe("ID блока документа"),
    type: z.enum(["paragraph"]).describe("Тип блока"),
    position: z.int().min(1).describe("Порядковый номер блока в документе"),
    value: z.string().describe("Значение поля"),
  })
  .describe("Блок документа - Параграф");

export type DocumentBlockParagraphV1Schema = z.infer<
  typeof documentBlockParagraphV1Schema
>;
