/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentCategoryV1Schema } from "./document-category-v1schema.ts";
import { documentMetaDtoV1Schema } from "./document-meta-dto-v1schema.ts";
import { paginationMetaV1Schema } from "./pagination-meta-v1schema.ts";

/**
 * @description Информация о категории
 */
export const documentCategoryResponseV1Schema = z
  .object({
    get category() {
      return documentCategoryV1Schema.describe("Список категорий");
    },
    get pageInfo() {
      return paginationMetaV1Schema.describe("Модель пагинации");
    },
    get documents() {
      return z
        .array(documentMetaDtoV1Schema.describe("Базовая модель документа"))
        .describe("Список документов в категории");
    },
  })
  .describe("Информация о категории");

export type DocumentCategoryResponseV1Schema = z.infer<
  typeof documentCategoryResponseV1Schema
>;
