/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Блок документа - Картинка
 */
export const documentBlockImageV1Schema = z
  .object({
    id: z.int().describe("ID блока"),
    type: z.enum(["image"]).describe("Тип блока"),
    position: z.int().min(1).describe("Порядковый номер блока в документе"),
    settings: z
      .object({
        title: z.string().describe("Название картинки"),
        src: z.url().describe("URL картинки"),
        width: z.optional(
          z.int().min(0).default(100).describe("Ширина картинки"),
        ),
        height: z.optional(
          z.int().min(0).default(100).describe("Высота картинки"),
        ),
      })
      .describe("Настройки блока с картинкой"),
  })
  .describe("Блок документа - Картинка");

export type DocumentBlockImageV1Schema = z.infer<
  typeof documentBlockImageV1Schema
>;
