/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Блок документа - Заголовок
 */
export const documentBlockTitleV1Schema = z
  .object({
    id: z.int().describe("ID блока документа"),
    type: z.enum(["header"]).describe("Тип блока"),
    level: z.enum(["1", "2", "3", "4", "5", "6"]).describe("Уровень заголовка"),
    position: z.int().min(1).describe("Порядковый номер блока в документе"),
    value: z.string().describe("Значение поля"),
  })
  .describe("Блок документа - Заголовок");

export type DocumentBlockTitleV1Schema = z.infer<
  typeof documentBlockTitleV1Schema
>;
