/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentBlockImageV1Schema } from "./document-block-image-v1schema.ts";
import { documentBlockParagraphV1Schema } from "./document-block-paragraph-v1schema.ts";
import { documentBlockTitleV1Schema } from "./document-block-title-v1schema.ts";
import { documentCategoryV1Schema } from "./document-category-v1schema.ts";
import { documentMetaDtoV1Schema } from "./document-meta-dto-v1schema.ts";

export const documentResponseV1Schema = z
  .lazy(() => documentMetaDtoV1Schema)
  .and(
    z.object({
      get content() {
        return z.array(
          z.union([
            documentBlockTitleV1Schema,
            documentBlockParagraphV1Schema,
            documentBlockImageV1Schema,
          ]),
        );
      },
      get category() {
        return documentCategoryV1Schema.describe("Список категорий");
      },
    }),
  );

export type DocumentResponseV1Schema = z.infer<typeof documentResponseV1Schema>;
