/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Модель создания / обновления категории документов
 */
export const documentCategoryRequestV1Schema = z
  .object({
    title: z.string().describe("Название категории"),
  })
  .describe("Модель создания / обновления категории документов");

export type DocumentCategoryRequestV1Schema = z.infer<
  typeof documentCategoryRequestV1Schema
>;
