/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";
import { documentTypeEnumV1Schema } from "./document-type-enum-v1schema.ts";
import { userMetaDataDtoV1Schema } from "./user-meta-data-dto-v1schema.ts";

/**
 * @description Базовая модель документа
 */
export const documentMetaDtoV1Schema = z
  .object({
    id: z.int().describe("ID документа"),
    title: z.string().describe("Название"),
    description: z.optional(z.string().describe("Описание документа")),
    createdAt: z.iso.datetime({ offset: true }).describe("Дата создания"),
    updatedAt: z.nullable(
      z.iso.datetime({ offset: true }).describe("Дата обновления"),
    ),
    comments: z.int().min(0).describe("Количество комментариев к документу"),
    get createdBy() {
      return userMetaDataDtoV1Schema.describe(
        "Ограниченные данные о пользователе",
      );
    },
    get type() {
      return documentTypeEnumV1Schema.describe("Тип документа");
    },
  })
  .describe("Базовая модель документа");

export type DocumentMetaDtoV1Schema = z.infer<typeof documentMetaDtoV1Schema>;
