/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Тип документа
 */
export const documentTypeEnumV1Schema = z
  .enum(["PUBLIC", "PRIVATE"])
  .describe("Тип документа");

export type DocumentTypeEnumV1Schema = z.infer<typeof documentTypeEnumV1Schema>;
