/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Список категорий
 */
export const documentCategoryV1Schema = z
  .object({
    id: z.uuid().describe("ID категории документа"),
    title: z.string().describe("Название категории"),
    countDocuments: z
      .int()
      .min(0)
      .describe("Количество документов в категории"),
  })
  .describe("Список категорий");

export type DocumentCategoryV1Schema = z.infer<typeof documentCategoryV1Schema>;
