/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type * as z from "zod";
import {
  getCommentsByDocumentId200Schema,
  getCommentsByDocumentId400Schema,
  getCommentsByDocumentId401Schema,
  getCommentsByDocumentId403Schema,
  getCommentsByDocumentId404Schema,
  getCommentsByDocumentId500Schema,
  getCommentsByDocumentIdQueryResponseSchema,
  getCommentsByDocumentIdPathParamsSchema,
} from "./comments-schema/get-comments-by-document-id-schema.ts";
import {
  createDocumentCategoryV1MutationRequestSchema,
  createDocumentCategoryV1201Schema,
  createDocumentCategoryV1400Schema,
  createDocumentCategoryV1401Schema,
  createDocumentCategoryV1403Schema,
  createDocumentCategoryV1500Schema,
  createDocumentCategoryV1MutationResponseSchema,
} from "./documents-schema/create-document-category-v1schema.ts";
import {
  getAllDocCategoriesV1200Schema,
  getAllDocCategoriesV1400Schema,
  getAllDocCategoriesV1401Schema,
  getAllDocCategoriesV1403Schema,
  getAllDocCategoriesV1500Schema,
  getAllDocCategoriesV1QueryResponseSchema,
} from "./documents-schema/get-all-doc-categories-v1schema.ts";
import {
  getDocumentById200Schema,
  getDocumentById400Schema,
  getDocumentById401Schema,
  getDocumentById403Schema,
  getDocumentById404Schema,
  getDocumentById500Schema,
  getDocumentByIdQueryResponseSchema,
  getDocumentByIdPathParamsSchema,
} from "./documents-schema/get-document-by-id-schema.ts";
import {
  getDocumentsCategoryById200Schema,
  getDocumentsCategoryById400Schema,
  getDocumentsCategoryById401Schema,
  getDocumentsCategoryById403Schema,
  getDocumentsCategoryById404Schema,
  getDocumentsCategoryById500Schema,
  getDocumentsCategoryByIdQueryResponseSchema,
  getDocumentsCategoryByIdPathParamsSchema,
  getDocumentsCategoryByIdQueryParamsSchema,
} from "./documents-schema/get-documents-category-by-id-schema.ts";
import {
  removeDocumentCategoryById204Schema,
  removeDocumentCategoryById400Schema,
  removeDocumentCategoryById401Schema,
  removeDocumentCategoryById403Schema,
  removeDocumentCategoryById404Schema,
  removeDocumentCategoryById500Schema,
  removeDocumentCategoryByIdMutationResponseSchema,
  removeDocumentCategoryByIdPathParamsSchema,
} from "./documents-schema/remove-document-category-by-id-schema.ts";
import {
  updateDocumentCategoryByIdMutationRequestSchema,
  updateDocumentCategoryById200Schema,
  updateDocumentCategoryById400Schema,
  updateDocumentCategoryById401Schema,
  updateDocumentCategoryById403Schema,
  updateDocumentCategoryById404Schema,
  updateDocumentCategoryById500Schema,
  updateDocumentCategoryByIdMutationResponseSchema,
  updateDocumentCategoryByIdPathParamsSchema,
} from "./documents-schema/update-document-category-by-id-schema.ts";

export type OperationSchema = {
  readonly request: z.ZodTypeAny | undefined;
  readonly parameters: {
    readonly path: z.ZodTypeAny | undefined;
    readonly query: z.ZodTypeAny | undefined;
    readonly header: z.ZodTypeAny | undefined;
  };
  readonly responses: {
    readonly [status: number]: z.ZodTypeAny;
    readonly default: z.ZodTypeAny;
  };
  readonly errors: {
    readonly [status: number]: z.ZodTypeAny;
  };
};

export type OperationsMap = Record<string, OperationSchema>;

export const operations = {
  getAllDocCategoriesV1: {
    request: undefined,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: getAllDocCategoriesV1200Schema,
      400: getAllDocCategoriesV1400Schema,
      401: getAllDocCategoriesV1401Schema,
      403: getAllDocCategoriesV1403Schema,
      500: getAllDocCategoriesV1500Schema,
      default: getAllDocCategoriesV1QueryResponseSchema,
    },
    errors: {
      400: getAllDocCategoriesV1400Schema,
      401: getAllDocCategoriesV1401Schema,
      403: getAllDocCategoriesV1403Schema,
      500: getAllDocCategoriesV1500Schema,
    },
  },
  createDocumentCategoryV1: {
    request: createDocumentCategoryV1MutationRequestSchema,
    parameters: {
      path: undefined,
      query: undefined,
      header: undefined,
    },
    responses: {
      201: createDocumentCategoryV1201Schema,
      400: createDocumentCategoryV1400Schema,
      401: createDocumentCategoryV1401Schema,
      403: createDocumentCategoryV1403Schema,
      500: createDocumentCategoryV1500Schema,
      default: createDocumentCategoryV1MutationResponseSchema,
    },
    errors: {
      400: createDocumentCategoryV1400Schema,
      401: createDocumentCategoryV1401Schema,
      403: createDocumentCategoryV1403Schema,
      500: createDocumentCategoryV1500Schema,
    },
  },
  getDocumentsCategoryById: {
    request: undefined,
    parameters: {
      path: getDocumentsCategoryByIdPathParamsSchema,
      query: getDocumentsCategoryByIdQueryParamsSchema,
      header: undefined,
    },
    responses: {
      200: getDocumentsCategoryById200Schema,
      400: getDocumentsCategoryById400Schema,
      401: getDocumentsCategoryById401Schema,
      403: getDocumentsCategoryById403Schema,
      404: getDocumentsCategoryById404Schema,
      500: getDocumentsCategoryById500Schema,
      default: getDocumentsCategoryByIdQueryResponseSchema,
    },
    errors: {
      400: getDocumentsCategoryById400Schema,
      401: getDocumentsCategoryById401Schema,
      403: getDocumentsCategoryById403Schema,
      404: getDocumentsCategoryById404Schema,
      500: getDocumentsCategoryById500Schema,
    },
  },
  updateDocumentCategoryById: {
    request: updateDocumentCategoryByIdMutationRequestSchema,
    parameters: {
      path: updateDocumentCategoryByIdPathParamsSchema,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: updateDocumentCategoryById200Schema,
      400: updateDocumentCategoryById400Schema,
      401: updateDocumentCategoryById401Schema,
      403: updateDocumentCategoryById403Schema,
      404: updateDocumentCategoryById404Schema,
      500: updateDocumentCategoryById500Schema,
      default: updateDocumentCategoryByIdMutationResponseSchema,
    },
    errors: {
      400: updateDocumentCategoryById400Schema,
      401: updateDocumentCategoryById401Schema,
      403: updateDocumentCategoryById403Schema,
      404: updateDocumentCategoryById404Schema,
      500: updateDocumentCategoryById500Schema,
    },
  },
  removeDocumentCategoryById: {
    request: undefined,
    parameters: {
      path: removeDocumentCategoryByIdPathParamsSchema,
      query: undefined,
      header: undefined,
    },
    responses: {
      204: removeDocumentCategoryById204Schema,
      400: removeDocumentCategoryById400Schema,
      401: removeDocumentCategoryById401Schema,
      403: removeDocumentCategoryById403Schema,
      404: removeDocumentCategoryById404Schema,
      500: removeDocumentCategoryById500Schema,
      default: removeDocumentCategoryByIdMutationResponseSchema,
    },
    errors: {
      400: removeDocumentCategoryById400Schema,
      401: removeDocumentCategoryById401Schema,
      403: removeDocumentCategoryById403Schema,
      404: removeDocumentCategoryById404Schema,
      500: removeDocumentCategoryById500Schema,
    },
  },
  getDocumentById: {
    request: undefined,
    parameters: {
      path: getDocumentByIdPathParamsSchema,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: getDocumentById200Schema,
      400: getDocumentById400Schema,
      401: getDocumentById401Schema,
      403: getDocumentById403Schema,
      404: getDocumentById404Schema,
      500: getDocumentById500Schema,
      default: getDocumentByIdQueryResponseSchema,
    },
    errors: {
      400: getDocumentById400Schema,
      401: getDocumentById401Schema,
      403: getDocumentById403Schema,
      404: getDocumentById404Schema,
      500: getDocumentById500Schema,
    },
  },
  getCommentsByDocumentId: {
    request: undefined,
    parameters: {
      path: getCommentsByDocumentIdPathParamsSchema,
      query: undefined,
      header: undefined,
    },
    responses: {
      200: getCommentsByDocumentId200Schema,
      400: getCommentsByDocumentId400Schema,
      401: getCommentsByDocumentId401Schema,
      403: getCommentsByDocumentId403Schema,
      404: getCommentsByDocumentId404Schema,
      500: getCommentsByDocumentId500Schema,
      default: getCommentsByDocumentIdQueryResponseSchema,
    },
    errors: {
      400: getCommentsByDocumentId400Schema,
      401: getCommentsByDocumentId401Schema,
      403: getCommentsByDocumentId403Schema,
      404: getCommentsByDocumentId404Schema,
      500: getCommentsByDocumentId500Schema,
    },
  },
} as const;

export const paths = {
  "/v1/documents/categories": {
    get: operations["getAllDocCategoriesV1"],
    post: operations["createDocumentCategoryV1"],
  },
  "/v1/documents/categories/{categoryId}": {
    get: operations["getDocumentsCategoryById"],
    put: operations["updateDocumentCategoryById"],
    delete: operations["removeDocumentCategoryById"],
  },
  "/v1/documents/{documentId}": {
    get: operations["getDocumentById"],
  },
  "/v1/documents/{documentId}/comments": {
    get: operations["getCommentsByDocumentId"],
  },
} as const;
