/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Модель пагинации
 */
export const paginationMetaV1Schema = z
  .object({
    empty: z.boolean().describe("Пришел ли пустой список проектов"),
    first: z.boolean().describe("Это была первая страница"),
    last: z.boolean().describe("Это была последняя страница"),
    number: z.int().min(0).describe("Номер страницы"),
    numberOfElements: z.int().min(0).describe("Число элементов на странице"),
    size: z.int().min(0).describe("Число элементов на странице"),
    totalElements: z.int().min(0).describe("Всего элементов храниться в API"),
    totalPages: z.int().min(1).describe("Всего страниц для пагинации"),
    sort: z
      .object({
        empty: z.boolean().describe("Пришел ли пустой список проектов"),
        sorted: z.boolean().describe("Отсортирован ли список"),
        unsorted: z.boolean().describe("Пришел ли не отсортированный список"),
      })
      .describe("Настройки сортировки"),
    pageable: z
      .object({
        offset: z.int().min(0).describe("Смещение пагинации"),
        pageNumber: z.int().min(0).describe("Номер страницы"),
        pageSize: z.int().min(0).describe("Число элементов на странице"),
        paged: z.boolean().describe("Неизвестное поле"),
        unpaged: z.boolean().describe("Неизвестное поле"),
        sort: z
          .object({
            empty: z.optional(
              z.boolean().describe("Пришел ли пустой список проектов"),
            ),
            sorted: z.optional(z.boolean().describe("Отсортирован ли список")),
            unsorted: z.optional(
              z.boolean().describe("Пришел ли не отсортированный список"),
            ),
          })
          .describe("Настройки сортировки"),
      })
      .describe("Настройки пагинации"),
  })
  .describe("Модель пагинации");

export type PaginationMetaV1Schema = z.infer<typeof paginationMetaV1Schema>;
