/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from "zod";

/**
 * @description Ограниченные данные о пользователе
 */
export const userMetaDataDtoV1Schema = z
  .object({
    id: z.int().describe("ID пользователя"),
    firstName: z.string().min(3).max(50).describe("Имя пользователя"),
    lastName: z.string().min(2).max(50).describe("Фамилия пользователя"),
    avatarUrl: z.nullable(z.url().describe("URL аватарки пользователя")),
  })
  .describe("Ограниченные данные о пользователе");

export type UserMetaDataDtoV1Schema = z.infer<typeof userMetaDataDtoV1Schema>;
