/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetAllDocCategoriesV1200,
  GetAllDocCategoriesV1400,
  GetAllDocCategoriesV1401,
  GetAllDocCategoriesV1403,
  GetAllDocCategoriesV1500,
  GetAllDocCategoriesV1QueryResponse,
} from "../../types/get-all-doc-categories-v1.ts";
import { faker } from "@faker-js/faker";
import { createDocumentCategoryListResponseV1 } from "../createDocumentCategoryListResponseV1.ts";

/**
 * @description Успешный запрос
 */
export function createGetAllDocCategoriesV1200(
  data?: Partial<GetAllDocCategoriesV1200>,
): GetAllDocCategoriesV1200 {
  faker.seed([100]);
  return createDocumentCategoryListResponseV1(data);
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createGetAllDocCategoriesV1400(
  data?: Partial<GetAllDocCategoriesV1400>,
): GetAllDocCategoriesV1400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createGetAllDocCategoriesV1401(
  data?: Partial<GetAllDocCategoriesV1401>,
): GetAllDocCategoriesV1401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createGetAllDocCategoriesV1403(
  data?: Partial<GetAllDocCategoriesV1403>,
): GetAllDocCategoriesV1403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createGetAllDocCategoriesV1500(
  data?: Partial<GetAllDocCategoriesV1500>,
): GetAllDocCategoriesV1500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createGetAllDocCategoriesV1QueryResponse(
  data?: Partial<GetAllDocCategoriesV1QueryResponse>,
): GetAllDocCategoriesV1QueryResponse {
  faker.seed([100]);
  return (
    data || faker.helpers.arrayElement<any>([createGetAllDocCategoriesV1200()])
  );
}
