/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  UpdateDocumentCategoryById200,
  UpdateDocumentCategoryById400,
  UpdateDocumentCategoryById401,
  UpdateDocumentCategoryById403,
  UpdateDocumentCategoryById404,
  UpdateDocumentCategoryById500,
  UpdateDocumentCategoryByIdMutationRequest,
  UpdateDocumentCategoryByIdMutationResponse,
  UpdateDocumentCategoryByIdPathParams,
} from "../../types/update-document-category-by-id.ts";
import { faker } from "@faker-js/faker";
import { createDocumentCategoryRequestV1 } from "../createDocumentCategoryRequestV1.ts";
import { createDocumentCategoryResponseV1 } from "../createDocumentCategoryResponseV1.ts";

export function createUpdateDocumentCategoryByIdPathParams(
  data?: Partial<UpdateDocumentCategoryByIdPathParams>,
): UpdateDocumentCategoryByIdPathParams {
  faker.seed([100]);
  return {
    ...{ categoryId: faker.number.int({ min: 1 }) },
    ...(data || {}),
  };
}

/**
 * @description Успешный запрос
 */
export function createUpdateDocumentCategoryById200(
  data?: Partial<UpdateDocumentCategoryById200>,
): UpdateDocumentCategoryById200 {
  faker.seed([100]);
  return createDocumentCategoryResponseV1(data);
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createUpdateDocumentCategoryById400(
  data?: Partial<UpdateDocumentCategoryById400>,
): UpdateDocumentCategoryById400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createUpdateDocumentCategoryById401(
  data?: Partial<UpdateDocumentCategoryById401>,
): UpdateDocumentCategoryById401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createUpdateDocumentCategoryById403(
  data?: Partial<UpdateDocumentCategoryById403>,
): UpdateDocumentCategoryById403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export function createUpdateDocumentCategoryById404(
  data?: Partial<UpdateDocumentCategoryById404>,
): UpdateDocumentCategoryById404 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createUpdateDocumentCategoryById500(
  data?: Partial<UpdateDocumentCategoryById500>,
): UpdateDocumentCategoryById500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createUpdateDocumentCategoryByIdMutationRequest(
  data?: Partial<UpdateDocumentCategoryByIdMutationRequest>,
): UpdateDocumentCategoryByIdMutationRequest {
  faker.seed([100]);
  return createDocumentCategoryRequestV1(data);
}

export function createUpdateDocumentCategoryByIdMutationResponse(
  data?: Partial<UpdateDocumentCategoryByIdMutationResponse>,
): UpdateDocumentCategoryByIdMutationResponse {
  faker.seed([100]);
  return (
    data ||
    faker.helpers.arrayElement<any>([createUpdateDocumentCategoryById200()])
  );
}
