/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetDocumentById200,
  GetDocumentById400,
  GetDocumentById401,
  GetDocumentById403,
  GetDocumentById404,
  GetDocumentById500,
  GetDocumentByIdPathParams,
  GetDocumentByIdQueryResponse,
} from "../../types/get-document-by-id.ts";
import { faker } from "@faker-js/faker";
import { createDocumentResponseV1 } from "../createDocumentResponseV1.ts";

export function createGetDocumentByIdPathParams(
  data?: Partial<GetDocumentByIdPathParams>,
): GetDocumentByIdPathParams {
  faker.seed([100]);
  return {
    ...{ documentId: faker.number.int({ min: 1 }) },
    ...(data || {}),
  };
}

/**
 * @description Успешный запрос
 */
export function createGetDocumentById200(
  data?: Partial<GetDocumentById200>,
): GetDocumentById200 {
  faker.seed([100]);
  return createDocumentResponseV1(data);
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createGetDocumentById400(
  data?: Partial<GetDocumentById400>,
): GetDocumentById400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createGetDocumentById401(
  data?: Partial<GetDocumentById401>,
): GetDocumentById401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createGetDocumentById403(
  data?: Partial<GetDocumentById403>,
): GetDocumentById403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export function createGetDocumentById404(
  data?: Partial<GetDocumentById404>,
): GetDocumentById404 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createGetDocumentById500(
  data?: Partial<GetDocumentById500>,
): GetDocumentById500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createGetDocumentByIdQueryResponse(
  data?: Partial<GetDocumentByIdQueryResponse>,
): GetDocumentByIdQueryResponse {
  faker.seed([100]);
  return data || faker.helpers.arrayElement<any>([createGetDocumentById200()]);
}
