/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetDocumentsCategoryById200,
  GetDocumentsCategoryById400,
  GetDocumentsCategoryById401,
  GetDocumentsCategoryById403,
  GetDocumentsCategoryById404,
  GetDocumentsCategoryById500,
  GetDocumentsCategoryByIdPathParams,
  GetDocumentsCategoryByIdQueryParams,
  GetDocumentsCategoryByIdQueryResponse,
} from "../../types/get-documents-category-by-id.ts";
import { faker } from "@faker-js/faker";
import { createDocumentCategoryResponseV1 } from "../createDocumentCategoryResponseV1.ts";

export function createGetDocumentsCategoryByIdPathParams(
  data?: Partial<GetDocumentsCategoryByIdPathParams>,
): GetDocumentsCategoryByIdPathParams {
  faker.seed([100]);
  return {
    ...{ categoryId: faker.number.int({ min: 1 }) },
    ...(data || {}),
  };
}

export function createGetDocumentsCategoryByIdQueryParams(
  data?: Partial<GetDocumentsCategoryByIdQueryParams>,
): GetDocumentsCategoryByIdQueryParams {
  faker.seed([100]);
  return {
    ...{
      page: faker.number.int({ min: 1 }),
      size: faker.number.int({ min: 1 }),
      sort: faker.helpers.multiple(() => faker.string.alpha()),
    },
    ...(data || {}),
  };
}

/**
 * @description Успешный запрос
 */
export function createGetDocumentsCategoryById200(
  data?: Partial<GetDocumentsCategoryById200>,
): GetDocumentsCategoryById200 {
  faker.seed([100]);
  return createDocumentCategoryResponseV1(data);
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createGetDocumentsCategoryById400(
  data?: Partial<GetDocumentsCategoryById400>,
): GetDocumentsCategoryById400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createGetDocumentsCategoryById401(
  data?: Partial<GetDocumentsCategoryById401>,
): GetDocumentsCategoryById401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createGetDocumentsCategoryById403(
  data?: Partial<GetDocumentsCategoryById403>,
): GetDocumentsCategoryById403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export function createGetDocumentsCategoryById404(
  data?: Partial<GetDocumentsCategoryById404>,
): GetDocumentsCategoryById404 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createGetDocumentsCategoryById500(
  data?: Partial<GetDocumentsCategoryById500>,
): GetDocumentsCategoryById500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createGetDocumentsCategoryByIdQueryResponse(
  data?: Partial<GetDocumentsCategoryByIdQueryResponse>,
): GetDocumentsCategoryByIdQueryResponse {
  faker.seed([100]);
  return (
    data ||
    faker.helpers.arrayElement<any>([createGetDocumentsCategoryById200()])
  );
}
