/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  RemoveDocumentCategoryById400,
  RemoveDocumentCategoryById401,
  RemoveDocumentCategoryById403,
  RemoveDocumentCategoryById404,
  RemoveDocumentCategoryById500,
  RemoveDocumentCategoryByIdMutationResponse,
  RemoveDocumentCategoryByIdPathParams,
} from "../../types/remove-document-category-by-id.ts";
import { faker } from "@faker-js/faker";

export function createRemoveDocumentCategoryByIdPathParams(
  data?: Partial<RemoveDocumentCategoryByIdPathParams>,
): RemoveDocumentCategoryByIdPathParams {
  faker.seed([100]);
  return {
    ...{ categoryId: faker.number.int({ min: 1 }) },
    ...(data || {}),
  };
}

/**
 * @description Успешный запрос
 */
export function createRemoveDocumentCategoryById204() {
  faker.seed([100]);
  return undefined;
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createRemoveDocumentCategoryById400(
  data?: Partial<RemoveDocumentCategoryById400>,
): RemoveDocumentCategoryById400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createRemoveDocumentCategoryById401(
  data?: Partial<RemoveDocumentCategoryById401>,
): RemoveDocumentCategoryById401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createRemoveDocumentCategoryById403(
  data?: Partial<RemoveDocumentCategoryById403>,
): RemoveDocumentCategoryById403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export function createRemoveDocumentCategoryById404(
  data?: Partial<RemoveDocumentCategoryById404>,
): RemoveDocumentCategoryById404 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createRemoveDocumentCategoryById500(
  data?: Partial<RemoveDocumentCategoryById500>,
): RemoveDocumentCategoryById500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createRemoveDocumentCategoryByIdMutationResponse(
  data?: Partial<RemoveDocumentCategoryByIdMutationResponse>,
): RemoveDocumentCategoryByIdMutationResponse {
  faker.seed([100]);
  return (
    data ||
    faker.helpers.arrayElement<any>([createRemoveDocumentCategoryById204()])
  );
}
