/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  CreateDocumentCategoryV1201,
  CreateDocumentCategoryV1400,
  CreateDocumentCategoryV1401,
  CreateDocumentCategoryV1403,
  CreateDocumentCategoryV1500,
  CreateDocumentCategoryV1MutationRequest,
  CreateDocumentCategoryV1MutationResponse,
} from "../../types/create-document-category-v1.ts";
import { faker } from "@faker-js/faker";
import { createDocumentCategoryRequestV1 } from "../createDocumentCategoryRequestV1.ts";
import { createDocumentCategoryResponseV1 } from "../createDocumentCategoryResponseV1.ts";

/**
 * @description Успешный запрос
 */
export function createCreateDocumentCategoryV1201(
  data?: Partial<CreateDocumentCategoryV1201>,
): CreateDocumentCategoryV1201 {
  faker.seed([100]);
  return createDocumentCategoryResponseV1(data);
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createCreateDocumentCategoryV1400(
  data?: Partial<CreateDocumentCategoryV1400>,
): CreateDocumentCategoryV1400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createCreateDocumentCategoryV1401(
  data?: Partial<CreateDocumentCategoryV1401>,
): CreateDocumentCategoryV1401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createCreateDocumentCategoryV1403(
  data?: Partial<CreateDocumentCategoryV1403>,
): CreateDocumentCategoryV1403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createCreateDocumentCategoryV1500(
  data?: Partial<CreateDocumentCategoryV1500>,
): CreateDocumentCategoryV1500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createCreateDocumentCategoryV1MutationRequest(
  data?: Partial<CreateDocumentCategoryV1MutationRequest>,
): CreateDocumentCategoryV1MutationRequest {
  faker.seed([100]);
  return createDocumentCategoryRequestV1(data);
}

export function createCreateDocumentCategoryV1MutationResponse(
  data?: Partial<CreateDocumentCategoryV1MutationResponse>,
): CreateDocumentCategoryV1MutationResponse {
  faker.seed([100]);
  return (
    data ||
    faker.helpers.arrayElement<any>([createCreateDocumentCategoryV1201()])
  );
}
