/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type {
  GetCommentsByDocumentId200,
  GetCommentsByDocumentId400,
  GetCommentsByDocumentId401,
  GetCommentsByDocumentId403,
  GetCommentsByDocumentId404,
  GetCommentsByDocumentId500,
  GetCommentsByDocumentIdPathParams,
  GetCommentsByDocumentIdQueryResponse,
} from "../../types/get-comments-by-document-id.ts";
import { faker } from "@faker-js/faker";
import { createCommentsListDtoV1 } from "../createCommentsListDtoV1.ts";

export function createGetCommentsByDocumentIdPathParams(
  data?: Partial<GetCommentsByDocumentIdPathParams>,
): GetCommentsByDocumentIdPathParams {
  faker.seed([100]);
  return {
    ...{ documentId: faker.number.int({ min: 1 }) },
    ...(data || {}),
  };
}

/**
 * @description Успешный запрос
 */
export function createGetCommentsByDocumentId200(
  data?: GetCommentsByDocumentId200,
): GetCommentsByDocumentId200 {
  faker.seed([100]);
  return createCommentsListDtoV1(data);
}

/**
 * @description Неверный запрос (Bad Request). В запросе содержатся некорректные данные.
 */
export function createGetCommentsByDocumentId400(
  data?: Partial<GetCommentsByDocumentId400>,
): GetCommentsByDocumentId400 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Не авторизован (Unauthorized). Требуется аутентификация
 */
export function createGetCommentsByDocumentId401(
  data?: Partial<GetCommentsByDocumentId401>,
): GetCommentsByDocumentId401 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Доступ запрещён (Forbidden). У пользователя нет прав для выполнения операции.
 */
export function createGetCommentsByDocumentId403(
  data?: Partial<GetCommentsByDocumentId403>,
): GetCommentsByDocumentId403 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ресурс не найден (Not Found). Запрашиваемый ресурс не существует.
 */
export function createGetCommentsByDocumentId404(
  data?: Partial<GetCommentsByDocumentId404>,
): GetCommentsByDocumentId404 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

/**
 * @description Ошибка сервера
 */
export function createGetCommentsByDocumentId500(
  data?: Partial<GetCommentsByDocumentId500>,
): GetCommentsByDocumentId500 {
  faker.seed([100]);
  return {
    ...{ message: faker.string.alpha() },
    ...(data || {}),
  };
}

export function createGetCommentsByDocumentIdQueryResponse(
  data?: Partial<GetCommentsByDocumentIdQueryResponse>,
): GetCommentsByDocumentIdQueryResponse {
  faker.seed([100]);
  return (
    data ||
    faker.helpers.arrayElement<any>([createGetCommentsByDocumentId200()])
  );
}
