// @ts-nocheck

/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/api/client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/api/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetAllDocCategoriesV1QueryResponse,
  GetAllDocCategoriesV1400,
  GetAllDocCategoriesV1401,
  GetAllDocCategoriesV1403,
  GetAllDocCategoriesV1500,
} from "../../../types/get-all-doc-categories-v1.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getAllDocCategoriesV1QueryResponseSchema } from "../../../zod/documents-schema/get-all-doc-categories-v1schema.ts";

export const getAllDocCategoriesV1QueryKey = () =>
  [{ url: "/v1/documents/categories" }] as const;

export type GetAllDocCategoriesV1QueryKey = ReturnType<
  typeof getAllDocCategoriesV1QueryKey
>;

/**
 * @description Получение списка всех категорий документов
 * @summary Список категорий документов
 * {@link /v1/documents/categories}
 */
export async function getAllDocCategoriesV1(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetAllDocCategoriesV1QueryResponse,
    ResponseErrorConfig<
      | GetAllDocCategoriesV1400
      | GetAllDocCategoriesV1401
      | GetAllDocCategoriesV1403
      | GetAllDocCategoriesV1500
    >,
    unknown
  >({
    method: "GET",
    url: `/v1/documents/categories`,
    baseURL: `/`,
    ...requestConfig,
  });
  return getAllDocCategoriesV1QueryResponseSchema.parse(res.data);
}

export function getAllDocCategoriesV1QueryOptions(
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getAllDocCategoriesV1QueryKey();
  return queryOptions<
    GetAllDocCategoriesV1QueryResponse,
    ResponseErrorConfig<
      | GetAllDocCategoriesV1400
      | GetAllDocCategoriesV1401
      | GetAllDocCategoriesV1403
      | GetAllDocCategoriesV1500
    >,
    GetAllDocCategoriesV1QueryResponse,
    typeof queryKey
  >({
    queryKey,
    queryFn: async ({ signal }) => {
      return getAllDocCategoriesV1({
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Получение списка всех категорий документов
 * @summary Список категорий документов
 * {@link /v1/documents/categories}
 */
export function useGetAllDocCategoriesV1<
  TData = GetAllDocCategoriesV1QueryResponse,
  TQueryData = GetAllDocCategoriesV1QueryResponse,
  TQueryKey extends QueryKey = GetAllDocCategoriesV1QueryKey,
>(
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetAllDocCategoriesV1QueryResponse,
        ResponseErrorConfig<
          | GetAllDocCategoriesV1400
          | GetAllDocCategoriesV1401
          | GetAllDocCategoriesV1403
          | GetAllDocCategoriesV1500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey = resolvedOptions?.queryKey ?? getAllDocCategoriesV1QueryKey();

  const query = useQuery(
    {
      ...getAllDocCategoriesV1QueryOptions(config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetAllDocCategoriesV1400
      | GetAllDocCategoriesV1401
      | GetAllDocCategoriesV1403
      | GetAllDocCategoriesV1500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
