// @ts-nocheck

/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/api/client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/api/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetDocumentByIdQueryResponse,
  GetDocumentByIdPathParams,
  GetDocumentById400,
  GetDocumentById401,
  GetDocumentById403,
  GetDocumentById404,
  GetDocumentById500,
} from "../../../types/get-document-by-id.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDocumentByIdQueryResponseSchema } from "../../../zod/documents-schema/get-document-by-id-schema.ts";

export const getDocumentByIdQueryKey = (
  documentId: GetDocumentByIdPathParams["documentId"] | undefined,
) =>
  [
    { url: "/v1/documents/:documentId", params: { documentId: documentId } },
  ] as const;

export type GetDocumentByIdQueryKey = ReturnType<
  typeof getDocumentByIdQueryKey
>;

/**
 * @description Получение категории документов по ID и краткого списка документов
 * @summary Получение категории документов по ID
 * {@link /v1/documents/:documentId}
 */
export async function getDocumentById(
  documentId: GetDocumentByIdPathParams["documentId"],
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDocumentByIdQueryResponse,
    ResponseErrorConfig<
      | GetDocumentById400
      | GetDocumentById401
      | GetDocumentById403
      | GetDocumentById404
      | GetDocumentById500
    >,
    unknown
  >({
    method: "GET",
    url: `/v1/documents/${documentId}`,
    baseURL: `/`,
    ...requestConfig,
  });
  return getDocumentByIdQueryResponseSchema.parse(res.data);
}

export function getDocumentByIdQueryOptions(
  documentId: GetDocumentByIdPathParams["documentId"] | undefined,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDocumentByIdQueryKey(documentId);
  return queryOptions<
    GetDocumentByIdQueryResponse,
    ResponseErrorConfig<
      | GetDocumentById400
      | GetDocumentById401
      | GetDocumentById403
      | GetDocumentById404
      | GetDocumentById500
    >,
    GetDocumentByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!documentId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getDocumentById(documentId!, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Получение категории документов по ID и краткого списка документов
 * @summary Получение категории документов по ID
 * {@link /v1/documents/:documentId}
 */
export function useGetDocumentById<
  TData = GetDocumentByIdQueryResponse,
  TQueryData = GetDocumentByIdQueryResponse,
  TQueryKey extends QueryKey = GetDocumentByIdQueryKey,
>(
  documentId: GetDocumentByIdPathParams["documentId"] | undefined,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDocumentByIdQueryResponse,
        ResponseErrorConfig<
          | GetDocumentById400
          | GetDocumentById401
          | GetDocumentById403
          | GetDocumentById404
          | GetDocumentById500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ?? getDocumentByIdQueryKey(documentId);

  const query = useQuery(
    {
      ...getDocumentByIdQueryOptions(documentId, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetDocumentById400
      | GetDocumentById401
      | GetDocumentById403
      | GetDocumentById404
      | GetDocumentById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
