// @ts-nocheck

/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import fetch from "@shared/api/client";
import type {
  Client,
  RequestConfig,
  ResponseErrorConfig,
} from "@shared/api/client";
import type {
  QueryKey,
  QueryClient,
  QueryObserverOptions,
  UseQueryResult,
} from "@tanstack/react-query";
import type {
  GetDocumentsCategoryByIdQueryResponse,
  GetDocumentsCategoryByIdPathParams,
  GetDocumentsCategoryByIdQueryParams,
  GetDocumentsCategoryById400,
  GetDocumentsCategoryById401,
  GetDocumentsCategoryById403,
  GetDocumentsCategoryById404,
  GetDocumentsCategoryById500,
} from "../../../types/get-documents-category-by-id.ts";
import { queryOptions, useQuery } from "@tanstack/react-query";
import { getDocumentsCategoryByIdQueryResponseSchema } from "../../../zod/documents-schema/get-documents-category-by-id-schema.ts";

export const getDocumentsCategoryByIdQueryKey = (
  categoryId: GetDocumentsCategoryByIdPathParams["categoryId"] | undefined,
  params?: GetDocumentsCategoryByIdQueryParams,
) =>
  [
    {
      url: "/v1/documents/categories/:categoryId",
      params: { categoryId: categoryId },
    },
    ...(params ? [params] : []),
  ] as const;

export type GetDocumentsCategoryByIdQueryKey = ReturnType<
  typeof getDocumentsCategoryByIdQueryKey
>;

/**
 * @description Получение документов по ID категории
 * @summary Получение документов по ID категории
 * {@link /v1/documents/categories/:categoryId}
 */
export async function getDocumentsCategoryById(
  categoryId: GetDocumentsCategoryByIdPathParams["categoryId"],
  params?: GetDocumentsCategoryByIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config;

  const res = await request<
    GetDocumentsCategoryByIdQueryResponse,
    ResponseErrorConfig<
      | GetDocumentsCategoryById400
      | GetDocumentsCategoryById401
      | GetDocumentsCategoryById403
      | GetDocumentsCategoryById404
      | GetDocumentsCategoryById500
    >,
    unknown
  >({
    method: "GET",
    url: `/v1/documents/categories/${categoryId}`,
    baseURL: `/`,
    params,
    ...requestConfig,
  });
  return getDocumentsCategoryByIdQueryResponseSchema.parse(res.data);
}

export function getDocumentsCategoryByIdQueryOptions(
  categoryId: GetDocumentsCategoryByIdPathParams["categoryId"] | undefined,
  params?: GetDocumentsCategoryByIdQueryParams,
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = getDocumentsCategoryByIdQueryKey(categoryId, params);
  return queryOptions<
    GetDocumentsCategoryByIdQueryResponse,
    ResponseErrorConfig<
      | GetDocumentsCategoryById400
      | GetDocumentsCategoryById401
      | GetDocumentsCategoryById403
      | GetDocumentsCategoryById404
      | GetDocumentsCategoryById500
    >,
    GetDocumentsCategoryByIdQueryResponse,
    typeof queryKey
  >({
    enabled: !!categoryId,
    queryKey,
    queryFn: async ({ signal }) => {
      return getDocumentsCategoryById(categoryId!, params, {
        ...config,
        signal: config.signal ?? signal,
      });
    },
  });
}

/**
 * @description Получение документов по ID категории
 * @summary Получение документов по ID категории
 * {@link /v1/documents/categories/:categoryId}
 */
export function useGetDocumentsCategoryById<
  TData = GetDocumentsCategoryByIdQueryResponse,
  TQueryData = GetDocumentsCategoryByIdQueryResponse,
  TQueryKey extends QueryKey = GetDocumentsCategoryByIdQueryKey,
>(
  categoryId: GetDocumentsCategoryByIdPathParams["categoryId"] | undefined,
  params?: GetDocumentsCategoryByIdQueryParams,
  options: {
    query?: Partial<
      QueryObserverOptions<
        GetDocumentsCategoryByIdQueryResponse,
        ResponseErrorConfig<
          | GetDocumentsCategoryById400
          | GetDocumentsCategoryById401
          | GetDocumentsCategoryById403
          | GetDocumentsCategoryById404
          | GetDocumentsCategoryById500
        >,
        TData,
        TQueryData,
        TQueryKey
      >
    > & { client?: QueryClient };
    client?: Partial<RequestConfig> & { client?: Client };
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {};
  const { client: queryClient, ...resolvedOptions } = queryConfig;
  const queryKey =
    resolvedOptions?.queryKey ??
    getDocumentsCategoryByIdQueryKey(categoryId, params);

  const query = useQuery(
    {
      ...getDocumentsCategoryByIdQueryOptions(categoryId, params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<
    TData,
    ResponseErrorConfig<
      | GetDocumentsCategoryById400
      | GetDocumentsCategoryById401
      | GetDocumentsCategoryById403
      | GetDocumentsCategoryById404
      | GetDocumentsCategoryById500
    >
  > & { queryKey: TQueryKey };

  query.queryKey = queryKey as TQueryKey;

  return query;
}
